# Generated by Django 5.2.10 on 2026-03-06 03:38

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='CodingCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('slug', models.SlugField(max_length=100, unique=True)),
                ('icon', models.CharField(default='bi-code-slash', help_text='Bootstrap icon class', max_length=50)),
                ('order', models.PositiveSmallIntegerField(default=0)),
            ],
            options={
                'verbose_name': 'Kategoriya',
                'verbose_name_plural': 'Kategoriyalar',
                'ordering': ['order', 'name'],
            },
        ),
        migrations.CreateModel(
            name='ProgrammingLanguage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, unique=True)),
                ('slug', models.SlugField(unique=True)),
                ('docker_image', models.CharField(help_text='Docker image nomi, masalan: python:3.12-slim', max_length=200)),
                ('compile_cmd', models.CharField(blank=True, help_text="Kompilatsiya buyrug'i (C++, Java). Bo'sh = interpretatsiya", max_length=500)),
                ('run_cmd', models.CharField(help_text="Ishga tushirish buyrug'i", max_length=500)),
                ('file_extension', models.CharField(help_text='Fayl kengaytmasi, masalan: .py', max_length=10)),
                ('monaco_language', models.CharField(help_text='Monaco editor tili, masalan: python', max_length=50)),
                ('is_active', models.BooleanField(default=True)),
                ('order', models.PositiveSmallIntegerField(default=0)),
            ],
            options={
                'verbose_name': 'Dasturlash tili',
                'verbose_name_plural': 'Dasturlash tillari',
                'ordering': ['order', 'name'],
            },
        ),
        migrations.CreateModel(
            name='CodingProblem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=300)),
                ('slug', models.SlugField(max_length=300, unique=True)),
                ('description', models.TextField(help_text='Masala sharti (HTML)')),
                ('input_format', models.TextField(help_text='Kirish formati')),
                ('output_format', models.TextField(help_text='Chiqish formati')),
                ('constraints', models.TextField(blank=True, help_text='Cheklovlar')),
                ('difficulty', models.CharField(choices=[('easy', 'Oson'), ('medium', "O'rta"), ('hard', 'Qiyin')], default='easy', max_length=10)),
                ('starter_code', models.JSONField(blank=True, default=dict, help_text='{"python": "def solve():\\n    pass", "cpp": "..."}')),
                ('time_limit', models.PositiveIntegerField(default=2, help_text='Sekundda (har bir test case uchun)')),
                ('memory_limit', models.PositiveIntegerField(default=256, help_text='MB da')),
                ('total_submissions', models.PositiveIntegerField(default=0)),
                ('accepted_submissions', models.PositiveIntegerField(default=0)),
                ('is_active', models.BooleanField(default=True)),
                ('order', models.PositiveIntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('category', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='problems', to='coding.codingcategory')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('languages', models.ManyToManyField(help_text="Qo'llab-quvvatlanadigan tillar", related_name='problems', to='coding.programminglanguage')),
            ],
            options={
                'verbose_name': 'Masala',
                'verbose_name_plural': 'Masalalar',
                'ordering': ['order', 'difficulty', 'title'],
            },
        ),
        migrations.CreateModel(
            name='CodeSubmission',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.TextField()),
                ('status', models.CharField(choices=[('pending', 'Kutilmoqda'), ('running', 'Ishlamoqda'), ('accepted', 'Qabul qilindi'), ('wrong_answer', "Noto'g'ri javob"), ('time_limit', 'Vaqt chegarasi'), ('memory_limit', 'Xotira chegarasi'), ('runtime_error', 'Runtime xato'), ('compilation_error', 'Kompilatsiya xatosi'), ('internal_error', 'Ichki xato')], default='pending', max_length=20)),
                ('results', models.JSONField(blank=True, default=list, help_text='Har bir test case natijasi')),
                ('passed_count', models.PositiveIntegerField(default=0)),
                ('total_count', models.PositiveIntegerField(default=0)),
                ('execution_time', models.FloatField(blank=True, help_text='Eng uzoq test case vaqti (ms)', null=True)),
                ('memory_used', models.FloatField(blank=True, help_text="Eng ko'p xotira (MB)", null=True)),
                ('error_message', models.TextField(blank=True)),
                ('is_sample_run', models.BooleanField(default=False, help_text='Faqat namuna testlar uchun sinov')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='code_submissions', to=settings.AUTH_USER_MODEL)),
                ('problem', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='submissions', to='coding.codingproblem')),
                ('language', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='coding.programminglanguage')),
            ],
            options={
                'verbose_name': 'Yuborish',
                'verbose_name_plural': 'Yuborishlar',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='TestCase',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('input_data', models.TextField(help_text="Kirish ma'lumotlari")),
                ('expected_output', models.TextField(help_text='Kutilgan chiqish')),
                ('is_sample', models.BooleanField(default=False, help_text="Foydalanuvchiga ko'rinadigan namuna")),
                ('order', models.PositiveSmallIntegerField(default=0)),
                ('problem', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='test_cases', to='coding.codingproblem')),
            ],
            options={
                'verbose_name': 'Test case',
                'verbose_name_plural': "Test case'lar",
                'ordering': ['order'],
            },
        ),
        migrations.CreateModel(
            name='UserCodingStats',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('problems_solved', models.PositiveIntegerField(default=0)),
                ('problems_attempted', models.PositiveIntegerField(default=0)),
                ('easy_solved', models.PositiveIntegerField(default=0)),
                ('medium_solved', models.PositiveIntegerField(default=0)),
                ('hard_solved', models.PositiveIntegerField(default=0)),
                ('total_submissions', models.PositiveIntegerField(default=0)),
                ('language_stats', models.JSONField(blank=True, default=dict, help_text='{"python": {"solved": 5, "submitted": 10}, ...}')),
                ('current_streak', models.PositiveIntegerField(default=0)),
                ('max_streak', models.PositiveIntegerField(default=0)),
                ('last_solved_date', models.DateField(blank=True, null=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='coding_stats', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Foydalanuvchi statistikasi',
                'verbose_name_plural': 'Foydalanuvchi statistikalari',
            },
        ),
    ]
