# Generated by Django 5.2.10 on 2026-01-19 05:11

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('tests_app', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Nomi')),
                ('slug', models.SlugField(unique=True, verbose_name='Slug')),
                ('description', models.TextField(blank=True, verbose_name='Tavsif')),
                ('icon', models.CharField(default='📰', max_length=50, verbose_name='Ikonka')),
                ('color', models.CharField(default='#3498db', max_length=7, verbose_name='Rang')),
                ('order', models.PositiveIntegerField(default=0, verbose_name='Tartib')),
                ('is_active', models.BooleanField(default=True, verbose_name='Faol')),
            ],
            options={
                'verbose_name': 'Kategoriya',
                'verbose_name_plural': 'Kategoriyalar',
                'ordering': ['order', 'name'],
            },
        ),
        migrations.CreateModel(
            name='Article',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('title', models.CharField(max_length=300, verbose_name='Sarlavha')),
                ('slug', models.SlugField(unique=True, verbose_name='Slug')),
                ('excerpt', models.TextField(max_length=500, verbose_name='Qisqa tavsif')),
                ('content', models.TextField(verbose_name='Mazmun')),
                ('article_type', models.CharField(choices=[('news', 'Yangilik'), ('announcement', "E'lon"), ('tip', 'Maslahat'), ('guide', "Qo'llanma"), ('update', 'Yangilanish')], default='news', max_length=20, verbose_name='Turi')),
                ('featured_image', models.ImageField(blank=True, null=True, upload_to='news/images/', verbose_name='Asosiy rasm')),
                ('meta_title', models.CharField(blank=True, max_length=70, verbose_name='Meta sarlavha')),
                ('meta_description', models.CharField(blank=True, max_length=160, verbose_name='Meta tavsif')),
                ('views_count', models.PositiveIntegerField(default=0, verbose_name="Ko'rishlar")),
                ('likes_count', models.PositiveIntegerField(default=0, verbose_name='Yoqtirishlar')),
                ('is_featured', models.BooleanField(default=False, verbose_name='Tavsiya etilgan')),
                ('is_pinned', models.BooleanField(default=False, verbose_name='Qadoqlangan')),
                ('is_published', models.BooleanField(default=False, verbose_name='Nashr etilgan')),
                ('published_at', models.DateTimeField(blank=True, null=True, verbose_name='Nashr vaqti')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('author', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='articles', to=settings.AUTH_USER_MODEL)),
                ('subject', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='articles', to='tests_app.subject')),
                ('category', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='articles', to='news.category', verbose_name='Kategoriya')),
            ],
            options={
                'verbose_name': 'Maqola',
                'verbose_name_plural': 'Maqolalar',
                'ordering': ['-is_pinned', '-published_at'],
            },
        ),
        migrations.CreateModel(
            name='Notification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('notification_type', models.CharField(choices=[('system', 'Tizim'), ('news', 'Yangilik'), ('competition', 'Musobaqa'), ('battle', 'Jang'), ('achievement', 'Yutuq'), ('friend', "Do'st"), ('reminder', 'Eslatma')], max_length=20, verbose_name='Turi')),
                ('title', models.CharField(max_length=200, verbose_name='Sarlavha')),
                ('message', models.TextField(verbose_name='Xabar')),
                ('link', models.CharField(blank=True, max_length=500, verbose_name='Havola')),
                ('related_id', models.PositiveIntegerField(blank=True, null=True, verbose_name="Bog'liq ID")),
                ('is_read', models.BooleanField(default=False, verbose_name="O'qilgan")),
                ('read_at', models.DateTimeField(blank=True, null=True, verbose_name="O'qilgan vaqt")),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notifications', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Bildirishnoma',
                'verbose_name_plural': 'Bildirishnomalar',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='ArticleLike',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('article', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='likes', to='news.article')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='article_likes', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Yoqtirish',
                'verbose_name_plural': 'Yoqtirishlar',
                'unique_together': {('article', 'user')},
            },
        ),
    ]
