# Generated by Django 5.2.10 on 2026-01-26 12:00

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='SystemBanner',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('message', models.CharField(max_length=500, verbose_name='Xabar matni')),
                ('banner_type', models.CharField(choices=[('info', "Ma'lumot"), ('warning', 'Ogohlantirish'), ('success', 'Muvaffaqiyat'), ('danger', 'Muhim'), ('promo', 'Reklama')], default='info', max_length=20, verbose_name='Turi')),
                ('link', models.URLField(blank=True, verbose_name='Havola')),
                ('link_text', models.CharField(blank=True, max_length=50, verbose_name='Havola matni')),
                ('icon', models.CharField(blank=True, max_length=50, verbose_name='Ikonka')),
                ('is_scrolling', models.BooleanField(default=True, verbose_name='Aylanib tursin')),
                ('scroll_speed', models.PositiveIntegerField(default=15, verbose_name='Tezlik (soniya)')),
                ('start_date', models.DateTimeField(blank=True, null=True, verbose_name='Boshlanish')),
                ('end_date', models.DateTimeField(blank=True, null=True, verbose_name='Tugash')),
                ('is_active', models.BooleanField(default=True, verbose_name='Faol')),
                ('is_dismissable', models.BooleanField(default=False, verbose_name="Yopsa bo'ladi")),
                ('order', models.PositiveIntegerField(default=0, verbose_name='Tartib')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Tizim banneri',
                'verbose_name_plural': 'Tizim bannerlari',
                'ordering': ['order', '-created_at'],
            },
        ),
    ]
