# Generated by Django 5.2.10 on 2026-01-19 05:11

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Banner',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='Sarlavha')),
                ('subtitle', models.CharField(blank=True, max_length=300, verbose_name="Qo'shimcha matn")),
                ('image', models.ImageField(upload_to='banners/', verbose_name='Rasm')),
                ('mobile_image', models.ImageField(blank=True, null=True, upload_to='banners/mobile/', verbose_name='Mobil rasm')),
                ('link', models.URLField(blank=True, verbose_name='Havola')),
                ('button_text', models.CharField(blank=True, max_length=50, verbose_name='Tugma matni')),
                ('position', models.CharField(choices=[('home_hero', 'Bosh sahifa Hero'), ('home_middle', "Bosh sahifa O'rta"), ('sidebar', 'Yon panel'), ('test_page', 'Test sahifasi'), ('result_page', 'Natija sahifasi')], max_length=20, verbose_name='Joylashuv')),
                ('start_date', models.DateTimeField(blank=True, null=True, verbose_name='Boshlanish')),
                ('end_date', models.DateTimeField(blank=True, null=True, verbose_name='Tugash')),
                ('views_count', models.PositiveIntegerField(default=0, verbose_name="Ko'rishlar")),
                ('clicks_count', models.PositiveIntegerField(default=0, verbose_name='Bosishlar')),
                ('order', models.PositiveIntegerField(default=0, verbose_name='Tartib')),
                ('is_active', models.BooleanField(default=True, verbose_name='Faol')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Banner',
                'verbose_name_plural': 'Bannerlar',
                'ordering': ['position', 'order'],
            },
        ),
        migrations.CreateModel(
            name='FAQ',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question', models.TextField(verbose_name='Savol')),
                ('answer', models.TextField(verbose_name='Javob')),
                ('category', models.CharField(choices=[('general', 'Umumiy'), ('account', 'Hisob'), ('test', 'Testlar'), ('competition', 'Musobaqalar'), ('payment', "To'lov"), ('technical', 'Texnik')], default='general', max_length=20, verbose_name='Kategoriya')),
                ('order', models.PositiveIntegerField(default=0, verbose_name='Tartib')),
                ('is_active', models.BooleanField(default=True, verbose_name='Faol')),
                ('views_count', models.PositiveIntegerField(default=0, verbose_name="Ko'rishlar")),
                ('helpful_count', models.PositiveIntegerField(default=0, verbose_name='Foydali')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'FAQ',
                'verbose_name_plural': 'FAQlar',
                'ordering': ['category', 'order'],
            },
        ),
        migrations.CreateModel(
            name='Partner',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='Nomi')),
                ('logo', models.ImageField(upload_to='partners/', verbose_name='Logo')),
                ('website', models.URLField(blank=True, verbose_name='Veb sayt')),
                ('description', models.TextField(blank=True, verbose_name='Tavsif')),
                ('order', models.PositiveIntegerField(default=0, verbose_name='Tartib')),
                ('is_active', models.BooleanField(default=True, verbose_name='Faol')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Hamkor',
                'verbose_name_plural': 'Hamkorlar',
                'ordering': ['order'],
            },
        ),
        migrations.CreateModel(
            name='SiteSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('site_name', models.CharField(default='TestMakon.uz', max_length=100, verbose_name='Sayt nomi')),
                ('site_tagline', models.CharField(default="AI Powered Ta'lim Platformasi", max_length=200, verbose_name='Slogan')),
                ('site_description', models.TextField(blank=True, verbose_name='Tavsif')),
                ('contact_email', models.EmailField(blank=True, max_length=254, verbose_name='Email')),
                ('contact_phone', models.CharField(blank=True, max_length=20, verbose_name='Telefon')),
                ('contact_address', models.TextField(blank=True, verbose_name='Manzil')),
                ('telegram_url', models.URLField(blank=True, verbose_name='Telegram')),
                ('instagram_url', models.URLField(blank=True, verbose_name='Instagram')),
                ('youtube_url', models.URLField(blank=True, verbose_name='YouTube')),
                ('facebook_url', models.URLField(blank=True, verbose_name='Facebook')),
                ('meta_title', models.CharField(blank=True, max_length=70, verbose_name='Meta sarlavha')),
                ('meta_description', models.CharField(blank=True, max_length=160, verbose_name='Meta tavsif')),
                ('meta_keywords', models.CharField(blank=True, max_length=255, verbose_name="Meta kalit so'zlar")),
                ('google_analytics_id', models.CharField(blank=True, max_length=50, verbose_name='Google Analytics ID')),
                ('yandex_metrika_id', models.CharField(blank=True, max_length=50, verbose_name='Yandex Metrika ID')),
                ('is_registration_open', models.BooleanField(default=True, verbose_name="Ro'yxatdan o'tish ochiq")),
                ('is_maintenance_mode', models.BooleanField(default=False, verbose_name='Texnik ishlar rejimi')),
                ('maintenance_message', models.TextField(blank=True, verbose_name='Texnik ishlar xabari')),
                ('total_users', models.PositiveIntegerField(default=0, verbose_name='Jami foydalanuvchilar')),
                ('total_tests', models.PositiveIntegerField(default=0, verbose_name='Jami testlar')),
                ('total_questions', models.PositiveIntegerField(default=0, verbose_name='Jami savollar')),
                ('total_attempts', models.PositiveIntegerField(default=0, verbose_name='Jami urinishlar')),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Sayt sozlamalari',
                'verbose_name_plural': 'Sayt sozlamalari',
            },
        ),
        migrations.CreateModel(
            name='ContactMessage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Ism')),
                ('email', models.EmailField(max_length=254, verbose_name='Email')),
                ('phone', models.CharField(blank=True, max_length=20, verbose_name='Telefon')),
                ('subject', models.CharField(max_length=200, verbose_name='Mavzu')),
                ('message', models.TextField(verbose_name='Xabar')),
                ('status', models.CharField(choices=[('new', 'Yangi'), ('read', "O'qilgan"), ('replied', 'Javob berilgan'), ('closed', 'Yopilgan')], default='new', max_length=20, verbose_name='Holat')),
                ('admin_notes', models.TextField(blank=True, verbose_name='Admin eslatmalari')),
                ('replied_at', models.DateTimeField(blank=True, null=True, verbose_name='Javob vaqti')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='contact_messages', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Aloqa xabari',
                'verbose_name_plural': 'Aloqa xabarlari',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Feedback',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('feedback_type', models.CharField(choices=[('bug', 'Xatolik'), ('feature', 'Yangi imkoniyat'), ('improvement', 'Yaxshilash'), ('complaint', 'Shikoyat'), ('praise', 'Maqtov'), ('other', 'Boshqa')], max_length=20, verbose_name='Turi')),
                ('priority', models.CharField(choices=[('low', 'Past'), ('medium', "O'rta"), ('high', 'Yuqori'), ('critical', 'Muhim')], default='medium', max_length=20, verbose_name='Muhimlik')),
                ('subject', models.CharField(max_length=200, verbose_name='Mavzu')),
                ('message', models.TextField(verbose_name='Xabar')),
                ('attachment', models.FileField(blank=True, null=True, upload_to='feedbacks/', verbose_name='Fayl')),
                ('page_url', models.URLField(blank=True, verbose_name='Sahifa URL')),
                ('is_resolved', models.BooleanField(default=False, verbose_name='Hal qilingan')),
                ('admin_response', models.TextField(blank=True, verbose_name='Admin javobi')),
                ('resolved_at', models.DateTimeField(blank=True, null=True, verbose_name='Hal qilingan vaqt')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='feedbacks', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Fikr-mulohaza',
                'verbose_name_plural': 'Fikr-mulohazalar',
                'ordering': ['-created_at'],
            },
        ),
    ]
