# Generated by Django 5.2.10 on 2026-01-19 05:11

import django.core.validators
import django.utils.timezone
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='Badge',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Nomi')),
                ('slug', models.SlugField(unique=True, verbose_name='Slug')),
                ('description', models.TextField(verbose_name='Tavsif')),
                ('badge_type', models.CharField(choices=[('streak', 'Streak'), ('test', 'Test'), ('competition', 'Musobaqa'), ('xp', 'XP'), ('special', 'Maxsus')], max_length=20, verbose_name='Turi')),
                ('icon', models.ImageField(upload_to='badges/', verbose_name='Ikonka')),
                ('xp_reward', models.PositiveIntegerField(default=0, verbose_name='XP mukofot')),
                ('requirement_value', models.PositiveIntegerField(default=0, verbose_name='Talab qilingan qiymat')),
                ('is_active', models.BooleanField(default=True, verbose_name='Faol')),
            ],
            options={
                'verbose_name': 'Badge',
                'verbose_name_plural': 'Badgelar',
                'ordering': ['badge_type', 'requirement_value'],
            },
        ),
        migrations.CreateModel(
            name='Friendship',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('pending', 'Kutilmoqda'), ('accepted', 'Qabul qilingan'), ('rejected', 'Rad etilgan'), ('blocked', 'Bloklangan')], default='pending', max_length=20, verbose_name='Holat')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': "Do'stlik",
                'verbose_name_plural': "Do'stliklar",
            },
        ),
        migrations.CreateModel(
            name='PhoneVerification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('phone_number', models.CharField(max_length=13, verbose_name='Telefon raqam')),
                ('code', models.CharField(max_length=6, verbose_name='Kod')),
                ('is_used', models.BooleanField(default=False, verbose_name='Ishlatilgan')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('expires_at', models.DateTimeField(verbose_name='Amal qilish muddati')),
            ],
            options={
                'verbose_name': 'Telefon tasdiqlash',
                'verbose_name_plural': 'Telefon tasdiqlashlar',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='UserActivity',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('activity_type', models.CharField(choices=[('login', 'Kirish'), ('test_complete', 'Test yakunlash'), ('competition_join', "Musobaqaga qo'shilish"), ('badge_earn', 'Badge olish'), ('level_up', "Level ko'tarilish"), ('friend_add', "Do'st qo'shish")], max_length=30, verbose_name='Faoliyat turi')),
                ('description', models.TextField(blank=True, verbose_name='Tavsif')),
                ('xp_earned', models.IntegerField(default=0, verbose_name='Olingan XP')),
                ('metadata', models.JSONField(blank=True, default=dict, verbose_name="Qo'shimcha ma'lumot")),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Faoliyat',
                'verbose_name_plural': 'Faoliyatlar',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='UserBadge',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('earned_at', models.DateTimeField(auto_now_add=True, verbose_name='Olingan vaqt')),
            ],
            options={
                'verbose_name': 'Foydalanuvchi badge',
                'verbose_name_plural': 'Foydalanuvchi badgelari',
                'ordering': ['-earned_at'],
            },
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('is_superuser', models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status')),
                ('is_staff', models.BooleanField(default=False, help_text='Designates whether the user can log into this admin site.', verbose_name='staff status')),
                ('is_active', models.BooleanField(default=True, help_text='Designates whether this user should be treated as active. Unselect this instead of deleting accounts.', verbose_name='active')),
                ('date_joined', models.DateTimeField(default=django.utils.timezone.now, verbose_name='date joined')),
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('phone_number', models.CharField(db_index=True, max_length=13, unique=True, validators=[django.core.validators.RegexValidator(message="Telefon raqam +998XXXXXXXXX formatida bo'lishi kerak", regex='^\\+998\\d{9}$')], verbose_name='Telefon raqam')),
                ('email', models.EmailField(blank=True, max_length=254, null=True, verbose_name='Email')),
                ('first_name', models.CharField(max_length=50, verbose_name='Ism')),
                ('last_name', models.CharField(max_length=50, verbose_name='Familiya')),
                ('middle_name', models.CharField(blank=True, max_length=50, verbose_name='Otasining ismi')),
                ('avatar', models.ImageField(blank=True, null=True, upload_to='avatars/%Y/%m/', verbose_name='Profil rasmi')),
                ('bio', models.TextField(blank=True, max_length=500, verbose_name='Bio')),
                ('birth_date', models.DateField(blank=True, null=True, verbose_name="Tug'ilgan sana")),
                ('education_level', models.CharField(choices=[('9', '9-sinf'), ('10', '10-sinf'), ('11', '11-sinf'), ('graduate', 'Bitiruvchi'), ('student', 'Talaba'), ('other', 'Boshqa')], default='11', max_length=20, verbose_name="Ta'lim darajasi")),
                ('school_name', models.CharField(blank=True, max_length=200, verbose_name='Maktab/Kollej nomi')),
                ('region', models.CharField(blank=True, max_length=100, verbose_name='Viloyat')),
                ('district', models.CharField(blank=True, max_length=100, verbose_name='Tuman')),
                ('xp_points', models.PositiveIntegerField(default=0, verbose_name='XP ballari')),
                ('level', models.CharField(choices=[('beginner', "Boshlang'ich"), ('elementary', 'Oddiy'), ('intermediate', "O'rta"), ('advanced', 'Yuqori'), ('expert', 'Ekspert'), ('master', 'Master'), ('legend', 'Legenda')], default='beginner', max_length=20, verbose_name='Daraja')),
                ('current_streak', models.PositiveIntegerField(default=0, verbose_name='Joriy streak')),
                ('longest_streak', models.PositiveIntegerField(default=0, verbose_name='Eng uzun streak')),
                ('last_activity_date', models.DateField(blank=True, null=True, verbose_name='Oxirgi faollik')),
                ('total_tests_taken', models.PositiveIntegerField(default=0, verbose_name='Jami testlar')),
                ('total_correct_answers', models.PositiveIntegerField(default=0, verbose_name="To'g'ri javoblar")),
                ('total_wrong_answers', models.PositiveIntegerField(default=0, verbose_name="Noto'g'ri javoblar")),
                ('average_score', models.FloatField(default=0.0, verbose_name="O'rtacha ball")),
                ('competitions_participated', models.PositiveIntegerField(default=0, verbose_name='Musobaqalar soni')),
                ('competitions_won', models.PositiveIntegerField(default=0, verbose_name='Yutilgan musobaqalar')),
                ('global_rank', models.PositiveIntegerField(blank=True, null=True, verbose_name='Umumiy reyting')),
                ('weekly_rank', models.PositiveIntegerField(blank=True, null=True, verbose_name='Haftalik reyting')),
                ('is_premium', models.BooleanField(default=False, verbose_name='Premium foydalanuvchi')),
                ('premium_until', models.DateTimeField(blank=True, null=True, verbose_name='Premium muddati')),
                ('is_phone_verified', models.BooleanField(default=False, verbose_name='Telefon tasdiqlangan')),
                ('is_email_verified', models.BooleanField(default=False, verbose_name='Email tasdiqlangan')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name="Ro'yxatdan o'tgan")),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Yangilangan')),
                ('groups', models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.group', verbose_name='groups')),
            ],
            options={
                'verbose_name': 'Foydalanuvchi',
                'verbose_name_plural': 'Foydalanuvchilar',
                'ordering': ['-created_at'],
            },
        ),
    ]
