# Generated by Django 5.2.10 on 2026-02-19 01:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_user_telegram_id_user_telegram_photo_url_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='TelegramAuthCode',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('telegram_id', models.BigIntegerField(verbose_name='Telegram ID')),
                ('telegram_username', models.CharField(blank=True, default='', max_length=100, verbose_name='Username')),
                ('telegram_first_name', models.CharField(blank=True, default='', max_length=100, verbose_name='Ism')),
                ('code', models.CharField(max_length=6, verbose_name='Kod')),
                ('is_used', models.BooleanField(default=False, verbose_name='Ishlatilgan')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('expires_at', models.DateTimeField(verbose_name='Amal qilish muddati')),
            ],
            options={
                'verbose_name': 'Telegram auth kod',
                'verbose_name_plural': 'Telegram auth kodlar',
                'ordering': ['-created_at'],
            },
        ),
    ]
