# Generated by Django 5.2.10 on 2026-01-19 05:11

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('tests_app', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Achievement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Nomi')),
                ('slug', models.SlugField(unique=True, verbose_name='Slug')),
                ('description', models.TextField(verbose_name='Tavsif')),
                ('category', models.CharField(choices=[('streak', 'Streak'), ('test', 'Test'), ('score', 'Ball'), ('competition', 'Musobaqa'), ('social', 'Ijtimoiy'), ('special', 'Maxsus')], max_length=20, verbose_name='Kategoriya')),
                ('rarity', models.CharField(choices=[('common', 'Oddiy'), ('uncommon', 'Noyob'), ('rare', 'Kam uchraydigan'), ('epic', 'Epik'), ('legendary', 'Afsonaviy')], default='common', max_length=20, verbose_name='Nodirligi')),
                ('icon', models.ImageField(upload_to='achievements/', verbose_name='Ikonka')),
                ('color', models.CharField(default='#FFD700', max_length=7, verbose_name='Rang')),
                ('requirement_type', models.CharField(max_length=50, verbose_name='Talab turi')),
                ('requirement_value', models.PositiveIntegerField(verbose_name='Talab qiymati')),
                ('xp_reward', models.PositiveIntegerField(default=0, verbose_name='XP mukofot')),
                ('total_earned', models.PositiveIntegerField(default=0, verbose_name='Jami olganlar')),
                ('is_active', models.BooleanField(default=True, verbose_name='Faol')),
                ('is_hidden', models.BooleanField(default=False, verbose_name='Yashirin')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Yutuq',
                'verbose_name_plural': 'Yutuqlar',
                'ordering': ['category', 'requirement_value'],
            },
        ),
        migrations.CreateModel(
            name='SeasonalLeaderboard',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Mavsum nomi')),
                ('slug', models.SlugField(unique=True, verbose_name='Slug')),
                ('description', models.TextField(blank=True, verbose_name='Tavsif')),
                ('start_date', models.DateField(verbose_name='Boshlanish')),
                ('end_date', models.DateField(verbose_name='Tugash')),
                ('prizes', models.JSONField(default=list, verbose_name='Sovrinlar')),
                ('is_active', models.BooleanField(default=True, verbose_name='Faol')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Mavsum',
                'verbose_name_plural': 'Mavsumlar',
                'ordering': ['-start_date'],
            },
        ),
        migrations.CreateModel(
            name='UserStats',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('total_tests', models.PositiveIntegerField(default=0, verbose_name='Jami testlar')),
                ('total_questions_answered', models.PositiveIntegerField(default=0, verbose_name='Jami javoblar')),
                ('total_correct', models.PositiveIntegerField(default=0, verbose_name="To'g'ri")),
                ('total_wrong', models.PositiveIntegerField(default=0, verbose_name="Noto'g'ri")),
                ('total_time_spent', models.PositiveIntegerField(default=0, verbose_name='Jami vaqt (daqiqa)')),
                ('average_time_per_question', models.FloatField(default=0.0, verbose_name="O'rtacha vaqt (soniya)")),
                ('subject_stats', models.JSONField(default=dict, verbose_name='Fan statistikasi')),
                ('best_score', models.FloatField(default=0.0, verbose_name='Eng yuqori ball')),
                ('best_streak', models.PositiveIntegerField(default=0, verbose_name='Eng uzun streak')),
                ('best_accuracy', models.FloatField(default=0.0, verbose_name='Eng yuqori aniqlik')),
                ('battles_won', models.PositiveIntegerField(default=0, verbose_name='Yutilgan janglar')),
                ('battles_lost', models.PositiveIntegerField(default=0, verbose_name='Yutqazilgan janglar')),
                ('battles_draw', models.PositiveIntegerField(default=0, verbose_name='Durrang janglar')),
                ('competitions_participated', models.PositiveIntegerField(default=0, verbose_name='Musobaqalar')),
                ('competitions_top3', models.PositiveIntegerField(default=0, verbose_name='Top 3 musobaqalar')),
                ('weekly_xp', models.PositiveIntegerField(default=0, verbose_name='Haftalik XP')),
                ('weekly_tests', models.PositiveIntegerField(default=0, verbose_name='Haftalik testlar')),
                ('weekly_correct', models.PositiveIntegerField(default=0, verbose_name="Haftalik to'g'ri")),
                ('today_xp', models.PositiveIntegerField(default=0, verbose_name='Bugungi XP')),
                ('today_tests', models.PositiveIntegerField(default=0, verbose_name='Bugungi testlar')),
                ('today_correct', models.PositiveIntegerField(default=0, verbose_name="Bugungi to'g'ri")),
                ('last_daily_reset', models.DateField(blank=True, null=True, verbose_name='Oxirgi kunlik reset')),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='stats', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Foydalanuvchi statistikasi',
                'verbose_name_plural': 'Foydalanuvchi statistikalari',
            },
        ),
        migrations.CreateModel(
            name='GlobalLeaderboard',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('period', models.CharField(choices=[('daily', 'Kunlik'), ('weekly', 'Haftalik'), ('monthly', 'Oylik'), ('all_time', 'Barcha vaqt')], max_length=20, verbose_name='Davr')),
                ('period_start', models.DateField(verbose_name='Davr boshi')),
                ('period_end', models.DateField(verbose_name='Davr oxiri')),
                ('rank', models.PositiveIntegerField(verbose_name="O'rin")),
                ('previous_rank', models.PositiveIntegerField(blank=True, null=True, verbose_name="Oldingi o'rin")),
                ('xp_earned', models.PositiveIntegerField(default=0, verbose_name='Olingan XP')),
                ('tests_completed', models.PositiveIntegerField(default=0, verbose_name='Testlar')),
                ('correct_answers', models.PositiveIntegerField(default=0, verbose_name="To'g'ri javoblar")),
                ('accuracy_rate', models.FloatField(default=0.0, verbose_name='Aniqlik (%)')),
                ('streak_days', models.PositiveIntegerField(default=0, verbose_name='Streak kunlar')),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='leaderboard_entries', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Umumiy reyting',
                'verbose_name_plural': 'Umumiy reytinglar',
                'ordering': ['rank'],
                'indexes': [models.Index(fields=['period', 'period_start', 'rank'], name='leaderboard_period_9da8b4_idx')],
                'unique_together': {('user', 'period', 'period_start')},
            },
        ),
        migrations.CreateModel(
            name='SeasonalParticipant',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rank', models.PositiveIntegerField(blank=True, null=True, verbose_name="O'rin")),
                ('total_xp', models.PositiveIntegerField(default=0, verbose_name='Jami XP')),
                ('total_tests', models.PositiveIntegerField(default=0, verbose_name='Jami testlar')),
                ('total_correct', models.PositiveIntegerField(default=0, verbose_name="To'g'ri javoblar")),
                ('accuracy_rate', models.FloatField(default=0.0, verbose_name='Aniqlik (%)')),
                ('joined_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('season', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='participants', to='leaderboard.seasonalleaderboard')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='seasonal_participations', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Mavsum ishtirokchisi',
                'verbose_name_plural': 'Mavsum ishtirokchilari',
                'ordering': ['rank'],
                'unique_together': {('season', 'user')},
            },
        ),
        migrations.CreateModel(
            name='SubjectLeaderboard',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('period', models.CharField(choices=[('weekly', 'Haftalik'), ('monthly', 'Oylik'), ('all_time', 'Barcha vaqt')], max_length=20, verbose_name='Davr')),
                ('period_start', models.DateField(verbose_name='Davr boshi')),
                ('rank', models.PositiveIntegerField(verbose_name="O'rin")),
                ('score', models.PositiveIntegerField(default=0, verbose_name='Ball')),
                ('tests_completed', models.PositiveIntegerField(default=0, verbose_name='Testlar')),
                ('accuracy_rate', models.FloatField(default=0.0, verbose_name='Aniqlik (%)')),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('subject', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='leaderboard_entries', to='tests_app.subject')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='subject_rankings', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Fan reytingi',
                'verbose_name_plural': 'Fan reytinglari',
                'ordering': ['rank'],
                'unique_together': {('user', 'subject', 'period', 'period_start')},
            },
        ),
        migrations.CreateModel(
            name='UserAchievement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('earned_at', models.DateTimeField(auto_now_add=True, verbose_name='Olingan vaqt')),
                ('is_notified', models.BooleanField(default=False, verbose_name='Xabar berilgan')),
                ('achievement', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='users', to='leaderboard.achievement')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='achievements', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Foydalanuvchi yutuqi',
                'verbose_name_plural': 'Foydalanuvchi yutuqlari',
                'ordering': ['-earned_at'],
                'unique_together': {('user', 'achievement')},
            },
        ),
    ]
