# Generated by Django 5.2.10 on 2026-01-19 05:11

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Subject',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Fan nomi')),
                ('slug', models.SlugField(unique=True, verbose_name='Slug')),
                ('description', models.TextField(blank=True, verbose_name='Tavsif')),
                ('icon', models.CharField(default='📚', max_length=50, verbose_name='Ikonka (emoji yoki class)')),
                ('color', models.CharField(default='#3498db', max_length=7, verbose_name='Rang (hex)')),
                ('image', models.ImageField(blank=True, null=True, upload_to='subjects/', verbose_name='Rasm')),
                ('order', models.PositiveIntegerField(default=0, verbose_name='Tartib')),
                ('total_tests', models.PositiveIntegerField(default=0, verbose_name='Jami testlar')),
                ('total_questions', models.PositiveIntegerField(default=0, verbose_name='Jami savollar')),
                ('is_active', models.BooleanField(default=True, verbose_name='Faol')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Fan',
                'verbose_name_plural': 'Fanlar',
                'ordering': ['order', 'name'],
            },
        ),
        migrations.CreateModel(
            name='Question',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('text', models.TextField(verbose_name='Savol matni')),
                ('image', models.ImageField(blank=True, null=True, upload_to='questions/', verbose_name='Rasm')),
                ('question_type', models.CharField(choices=[('single', "Bitta to'g'ri javob"), ('multiple', "Ko'p to'g'ri javob"), ('true_false', "To'g'ri/Noto'g'ri"), ('fill_blank', "Bo'sh joyni to'ldiring")], default='single', max_length=20, verbose_name='Savol turi')),
                ('difficulty', models.CharField(choices=[('easy', 'Oson'), ('medium', "O'rta"), ('hard', 'Qiyin'), ('expert', 'Ekspert')], default='medium', max_length=20, verbose_name='Qiyinlik')),
                ('points', models.PositiveIntegerField(default=1, verbose_name='Ball')),
                ('time_limit', models.PositiveIntegerField(default=60, verbose_name='Vaqt (soniya)')),
                ('explanation', models.TextField(blank=True, verbose_name='Tushuntirish')),
                ('hint', models.TextField(blank=True, verbose_name='Maslahat')),
                ('times_answered', models.PositiveIntegerField(default=0, verbose_name='Javob berilgan')),
                ('times_correct', models.PositiveIntegerField(default=0, verbose_name="To'g'ri javoblar")),
                ('source', models.CharField(blank=True, max_length=200, verbose_name='Manba')),
                ('year', models.PositiveIntegerField(blank=True, null=True, verbose_name='Yil')),
                ('is_active', models.BooleanField(default=True, verbose_name='Faol')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_questions', to=settings.AUTH_USER_MODEL)),
                ('subject', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='questions', to='tests_app.subject', verbose_name='Fan')),
            ],
            options={
                'verbose_name': 'Savol',
                'verbose_name_plural': 'Savollar',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Answer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.TextField(verbose_name='Javob matni')),
                ('image', models.ImageField(blank=True, null=True, upload_to='answers/', verbose_name='Rasm')),
                ('is_correct', models.BooleanField(default=False, verbose_name="To'g'ri javob")),
                ('order', models.PositiveIntegerField(default=0, verbose_name='Tartib')),
                ('question', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='answers', to='tests_app.question', verbose_name='Savol')),
            ],
            options={
                'verbose_name': 'Javob',
                'verbose_name_plural': 'Javoblar',
                'ordering': ['order'],
            },
        ),
        migrations.CreateModel(
            name='Test',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('title', models.CharField(max_length=200, verbose_name='Sarlavha')),
                ('slug', models.SlugField(unique=True, verbose_name='Slug')),
                ('description', models.TextField(blank=True, verbose_name='Tavsif')),
                ('test_type', models.CharField(choices=[('practice', 'Mashq'), ('exam', 'Imtihon'), ('block', 'Blok test'), ('topic', "Mavzu bo'yicha"), ('quick', 'Tezkor test'), ('competition', 'Musobaqa')], default='practice', max_length=20, verbose_name='Test turi')),
                ('time_limit', models.PositiveIntegerField(default=60, verbose_name='Vaqt (daqiqa)')),
                ('question_count', models.PositiveIntegerField(default=30, verbose_name='Savollar soni')),
                ('passing_score', models.PositiveIntegerField(default=60, verbose_name="O'tish bali (%)")),
                ('shuffle_questions', models.BooleanField(default=True, verbose_name='Savollarni aralashtirish')),
                ('shuffle_answers', models.BooleanField(default=True, verbose_name='Javoblarni aralashtirish')),
                ('show_correct_answers', models.BooleanField(default=True, verbose_name="To'g'ri javoblarni ko'rsatish")),
                ('is_active', models.BooleanField(default=True, verbose_name='Faol')),
                ('is_premium', models.BooleanField(default=False, verbose_name='Premium')),
                ('start_date', models.DateTimeField(blank=True, null=True, verbose_name='Boshlanish vaqti')),
                ('end_date', models.DateTimeField(blank=True, null=True, verbose_name='Tugash vaqti')),
                ('total_attempts', models.PositiveIntegerField(default=0, verbose_name='Jami urinishlar')),
                ('average_score', models.FloatField(default=0.0, verbose_name="O'rtacha ball")),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_tests', to=settings.AUTH_USER_MODEL)),
                ('subject', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='tests', to='tests_app.subject', verbose_name='Fan')),
                ('subjects', models.ManyToManyField(blank=True, related_name='block_tests', to='tests_app.subject', verbose_name='Fanlar (blok test uchun)')),
            ],
            options={
                'verbose_name': 'Test',
                'verbose_name_plural': 'Testlar',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='TestAttempt',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('status', models.CharField(choices=[('started', 'Boshlangan'), ('in_progress', 'Davom etmoqda'), ('completed', 'Yakunlangan'), ('timeout', 'Vaqt tugagan'), ('abandoned', 'Tashlab ketilgan')], default='started', max_length=20, verbose_name='Holat')),
                ('current_question', models.PositiveIntegerField(default=0, verbose_name='Joriy savol')),
                ('total_questions', models.PositiveIntegerField(default=0, verbose_name='Jami savollar')),
                ('correct_answers', models.PositiveIntegerField(default=0, verbose_name="To'g'ri javoblar")),
                ('wrong_answers', models.PositiveIntegerField(default=0, verbose_name="Noto'g'ri javoblar")),
                ('skipped_questions', models.PositiveIntegerField(default=0, verbose_name="O'tkazib yuborilgan")),
                ('score', models.FloatField(default=0.0, verbose_name='Ball')),
                ('percentage', models.FloatField(default=0.0, verbose_name='Foiz')),
                ('xp_earned', models.PositiveIntegerField(default=0, verbose_name='Olingan XP')),
                ('time_spent', models.PositiveIntegerField(default=0, verbose_name='Sarflangan vaqt (soniya)')),
                ('started_at', models.DateTimeField(auto_now_add=True, verbose_name='Boshlangan vaqt')),
                ('completed_at', models.DateTimeField(blank=True, null=True, verbose_name='Yakunlangan vaqt')),
                ('ai_analysis', models.TextField(blank=True, verbose_name='AI tahlili')),
                ('ai_recommendations', models.JSONField(blank=True, default=list, verbose_name='AI tavsiyalari')),
                ('weak_topics', models.JSONField(blank=True, default=list, verbose_name='Sust mavzular')),
                ('strong_topics', models.JSONField(blank=True, default=list, verbose_name='Kuchli mavzular')),
                ('test', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='attempts', to='tests_app.test', verbose_name='Test')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='test_attempts', to=settings.AUTH_USER_MODEL, verbose_name='Foydalanuvchi')),
            ],
            options={
                'verbose_name': 'Test urinishi',
                'verbose_name_plural': 'Test urinishlari',
                'ordering': ['-started_at'],
            },
        ),
        migrations.CreateModel(
            name='AttemptAnswer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_correct', models.BooleanField(default=False, verbose_name="To'g'ri")),
                ('time_spent', models.PositiveIntegerField(default=0, verbose_name='Sarflangan vaqt (soniya)')),
                ('answered_at', models.DateTimeField(auto_now_add=True, verbose_name='Javob vaqti')),
                ('selected_answer', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='selections', to='tests_app.answer', verbose_name='Tanlangan javob')),
                ('question', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='attempt_answers', to='tests_app.question', verbose_name='Savol')),
                ('attempt', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='answers', to='tests_app.testattempt', verbose_name='Urinish')),
            ],
            options={
                'verbose_name': 'Javob',
                'verbose_name_plural': 'Javoblar',
                'ordering': ['answered_at'],
            },
        ),
        migrations.CreateModel(
            name='TestQuestion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order', models.PositiveIntegerField(default=0, verbose_name='Tartib')),
                ('question', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tests_app.question')),
                ('test', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tests_app.test')),
            ],
            options={
                'verbose_name': 'Test savoli',
                'verbose_name_plural': 'Test savollari',
                'ordering': ['order'],
            },
        ),
        migrations.AddField(
            model_name='test',
            name='questions',
            field=models.ManyToManyField(related_name='tests', through='tests_app.TestQuestion', to='tests_app.question', verbose_name='Savollar'),
        ),
        migrations.CreateModel(
            name='Topic',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='Mavzu nomi')),
                ('slug', models.SlugField(verbose_name='Slug')),
                ('description', models.TextField(blank=True, verbose_name='Tavsif')),
                ('order', models.PositiveIntegerField(default=0, verbose_name='Tartib')),
                ('is_active', models.BooleanField(default=True, verbose_name='Faol')),
                ('parent', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='subtopics', to='tests_app.topic', verbose_name='Yuqori mavzu')),
                ('subject', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='topics', to='tests_app.subject', verbose_name='Fan')),
            ],
            options={
                'verbose_name': 'Mavzu',
                'verbose_name_plural': 'Mavzular',
                'ordering': ['subject', 'order', 'name'],
            },
        ),
        migrations.AddField(
            model_name='question',
            name='topic',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='questions', to='tests_app.topic', verbose_name='Mavzu'),
        ),
        migrations.CreateModel(
            name='SavedQuestion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('note', models.TextField(blank=True, verbose_name='Eslatma')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('question', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='saved_by', to='tests_app.question')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='saved_questions', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Saqlangan savol',
                'verbose_name_plural': 'Saqlangan savollar',
                'ordering': ['-created_at'],
                'unique_together': {('user', 'question')},
            },
        ),
        migrations.AddIndex(
            model_name='testattempt',
            index=models.Index(fields=['user', 'test'], name='tests_app_t_user_id_455eaa_idx'),
        ),
        migrations.AddIndex(
            model_name='testattempt',
            index=models.Index(fields=['status'], name='tests_app_t_status_6834b2_idx'),
        ),
        migrations.AddIndex(
            model_name='testattempt',
            index=models.Index(fields=['started_at'], name='tests_app_t_started_8620f8_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='attemptanswer',
            unique_together={('attempt', 'question')},
        ),
        migrations.AlterUniqueTogether(
            name='testquestion',
            unique_together={('test', 'question')},
        ),
        migrations.AlterUniqueTogether(
            name='topic',
            unique_together={('subject', 'slug')},
        ),
        migrations.AddIndex(
            model_name='question',
            index=models.Index(fields=['subject', 'difficulty'], name='tests_app_q_subject_c5874b_idx'),
        ),
        migrations.AddIndex(
            model_name='question',
            index=models.Index(fields=['topic'], name='tests_app_q_topic_i_6b1764_idx'),
        ),
        migrations.AddIndex(
            model_name='question',
            index=models.Index(fields=['is_active'], name='tests_app_q_is_acti_49a0cb_idx'),
        ),
    ]
