# Generated by Django 5.2.10 on 2026-03-12 10:29

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('tests_app', '0002_useranalyticssummary_userstudysession_dailyuserstats_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='CertMock',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('title', models.CharField(max_length=200, verbose_name='Mock nomi')),
                ('slug', models.SlugField(max_length=200, verbose_name='Slug')),
                ('description', models.TextField(blank=True, verbose_name='Tavsif')),
                ('year', models.PositiveIntegerField(blank=True, null=True, verbose_name='Yil')),
                ('version', models.CharField(blank=True, max_length=20, verbose_name='Variant')),
                ('is_free', models.BooleanField(default=False, verbose_name='Bepul')),
                ('is_active', models.BooleanField(default=True, verbose_name='Faol')),
                ('time_limit', models.PositiveIntegerField(default=120, verbose_name='Vaqt (daqiqa)')),
                ('passing_score', models.PositiveIntegerField(default=56, verbose_name="O'tish bali (%)")),
                ('max_attempts', models.PositiveIntegerField(default=0, verbose_name='Max urinishlar (0=cheksiz)')),
                ('questions_count', models.PositiveIntegerField(default=0, verbose_name='Savollar soni')),
                ('total_points', models.PositiveIntegerField(default=0, verbose_name='Jami ball')),
                ('order', models.PositiveIntegerField(default=0, verbose_name='Tartib')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Mock Test',
                'verbose_name_plural': 'Mock Testlar',
                'ordering': ['cert_subject', 'order', '-year'],
            },
        ),
        migrations.CreateModel(
            name='CertMockAttempt',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('status', models.CharField(choices=[('started', 'Boshlangan'), ('in_progress', 'Davom etmoqda'), ('completed', 'Yakunlangan'), ('timeout', 'Vaqt tugagan')], default='started', max_length=20, verbose_name='Holat')),
                ('started_at', models.DateTimeField(auto_now_add=True, verbose_name='Boshlangan')),
                ('completed_at', models.DateTimeField(blank=True, null=True, verbose_name='Yakunlangan')),
                ('time_spent', models.PositiveIntegerField(default=0, verbose_name='Sarflangan vaqt (soniya)')),
                ('total_questions', models.PositiveIntegerField(default=0, verbose_name='Jami savollar')),
                ('correct_answers', models.PositiveIntegerField(default=0, verbose_name="To'g'ri")),
                ('wrong_answers', models.PositiveIntegerField(default=0, verbose_name="Noto'g'ri")),
                ('skipped_questions', models.PositiveIntegerField(default=0, verbose_name="O'tkazilgan")),
                ('total_points', models.PositiveIntegerField(default=0, verbose_name='Jami ball')),
                ('earned_points', models.PositiveIntegerField(default=0, verbose_name='Olingan ball')),
                ('percentage', models.FloatField(default=0.0, verbose_name='Foiz')),
                ('grade', models.CharField(blank=True, choices=[('A+', 'A+ — Mukammal'), ('A', "A — A'lo"), ('B', 'B — Yaxshi'), ('C', 'C — Qoniqarli'), ('D', "D — O'rtacha"), ('F', 'F — Yaxshilash kerak')], max_length=2, verbose_name='Baho')),
                ('feedback', models.CharField(blank=True, max_length=300, verbose_name='Fikr')),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True, verbose_name='IP')),
                ('mock', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='attempts', to='certificate.certmock', verbose_name='Mock')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cert_attempts', to=settings.AUTH_USER_MODEL, verbose_name='Foydalanuvchi')),
            ],
            options={
                'verbose_name': 'Mock Urinishi',
                'verbose_name_plural': 'Mock Urinishlari',
                'ordering': ['-started_at'],
            },
        ),
        migrations.CreateModel(
            name='CertQuestion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('number', models.PositiveIntegerField(verbose_name='Savol raqami')),
                ('question_type', models.CharField(choices=[('choice', 'A/B/C/D tanlov (1–32)'), ('grouped_af', 'A–F guruhlangan (33–35)'), ('short_open', 'Qisqa ochiq javob'), ('multi_part', "Ko'p qismli (a/b/c/d)")], max_length=20, verbose_name='Savol turi')),
                ('text', models.TextField(blank=True, verbose_name='Savol matni')),
                ('image', models.ImageField(blank=True, null=True, upload_to='cert/questions/', verbose_name='Rasm')),
                ('points', models.PositiveIntegerField(default=1, verbose_name='Ball')),
                ('difficulty', models.CharField(choices=[('easy', 'Oson'), ('medium', "O'rta"), ('hard', 'Qiyin')], default='medium', max_length=10, verbose_name='Qiyinlik')),
                ('source', models.CharField(blank=True, max_length=200, verbose_name='Manba')),
                ('year', models.PositiveIntegerField(blank=True, null=True, verbose_name='Yil')),
                ('explanation', models.TextField(blank=True, verbose_name='Tushuntirish')),
                ('hint', models.TextField(blank=True, verbose_name='Maslahat')),
                ('requires_manual_check', models.BooleanField(default=False, verbose_name="Qo'lda tekshirish")),
                ('is_active', models.BooleanField(default=True, verbose_name='Faol')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('mock', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='questions', to='certificate.certmock', verbose_name='Mock')),
                ('topic', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='tests_app.topic', verbose_name='Mavzu')),
            ],
            options={
                'verbose_name': 'Savol',
                'verbose_name_plural': 'Savollar',
                'ordering': ['number'],
                'unique_together': {('mock', 'number')},
            },
        ),
        migrations.CreateModel(
            name='CertMultiPart',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('part_label', models.CharField(max_length=2, verbose_name='Part (a/b/c/d)')),
                ('text', models.TextField(verbose_name='Part savoli')),
                ('image', models.ImageField(blank=True, null=True, upload_to='cert/parts/', verbose_name='Rasm')),
                ('points', models.PositiveIntegerField(default=1, verbose_name='Ball')),
                ('correct_answer', models.TextField(blank=True, verbose_name="To'g'ri javob")),
                ('answer_type', models.CharField(choices=[('text', 'Matn'), ('integer', 'Butun son'), ('float', 'Kasr son'), ('choice', 'Variant tanlov')], default='text', max_length=10, verbose_name='Javob turi')),
                ('requires_manual_check', models.BooleanField(default=False, verbose_name="Qo'lda tekshirish")),
                ('tolerance', models.FloatField(default=0.0, verbose_name="Og'ish")),
                ('order', models.PositiveIntegerField(default=0, verbose_name='Tartib')),
                ('question', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='parts', to='certificate.certquestion', verbose_name='Savol')),
            ],
            options={
                'verbose_name': 'Part',
                'verbose_name_plural': 'Partlar',
                'ordering': ['order', 'part_label'],
            },
        ),
        migrations.CreateModel(
            name='CertGroupedOption',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('label', models.CharField(max_length=1, verbose_name='Harf')),
                ('text', models.TextField(verbose_name='Matn')),
                ('order', models.PositiveIntegerField(default=0, verbose_name='Tartib')),
                ('question', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='grouped_options', to='certificate.certquestion', verbose_name='Savol')),
            ],
            options={
                'verbose_name': 'Guruh varianti',
                'verbose_name_plural': 'Guruh variantlari',
                'ordering': ['order', 'label'],
            },
        ),
        migrations.CreateModel(
            name='CertGroupedItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('item_number', models.PositiveIntegerField(verbose_name='Item raqami')),
                ('text', models.TextField(verbose_name='Item matni')),
                ('correct_option', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='correct_for_items', to='certificate.certgroupedoption', verbose_name="To'g'ri variant")),
                ('question', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='grouped_items', to='certificate.certquestion', verbose_name='Savol')),
            ],
            options={
                'verbose_name': 'Guruh elementi',
                'verbose_name_plural': 'Guruh elementlari',
                'ordering': ['item_number'],
            },
        ),
        migrations.CreateModel(
            name='CertChoice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('label', models.CharField(max_length=1, verbose_name='Harf')),
                ('text', models.TextField(verbose_name='Matn')),
                ('image', models.ImageField(blank=True, null=True, upload_to='cert/choices/', verbose_name='Rasm')),
                ('is_correct', models.BooleanField(default=False, verbose_name="To'g'ri javob")),
                ('order', models.PositiveIntegerField(default=0, verbose_name='Tartib')),
                ('question', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='choices', to='certificate.certquestion', verbose_name='Savol')),
            ],
            options={
                'verbose_name': 'Variant',
                'verbose_name_plural': 'Variantlar',
                'ordering': ['order', 'label'],
            },
        ),
        migrations.CreateModel(
            name='CertShortOpen',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('correct_answer', models.TextField(verbose_name="To'g'ri javob")),
                ('answer_type', models.CharField(choices=[('text', 'Matn'), ('integer', 'Butun son'), ('float', 'Kasr son'), ('formula', 'Formula')], default='text', max_length=10, verbose_name='Javob turi')),
                ('tolerance', models.FloatField(default=0.0, verbose_name="Og'ish (float uchun)")),
                ('case_sensitive', models.BooleanField(default=False, verbose_name='Katta-kichik harf')),
                ('question', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='short_open', to='certificate.certquestion', verbose_name='Savol')),
            ],
            options={
                'verbose_name': 'Qisqa ochiq javob',
                'verbose_name_plural': 'Qisqa ochiq javoblar',
            },
        ),
        migrations.CreateModel(
            name='CertSubject',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.TextField(blank=True, verbose_name="Qo'shimcha tavsif")),
                ('order', models.PositiveIntegerField(default=0, verbose_name='Tartib')),
                ('is_active', models.BooleanField(default=True, verbose_name='Faol')),
                ('total_mocks', models.PositiveIntegerField(default=0, verbose_name='Jami mock testlar')),
                ('free_mocks', models.PositiveIntegerField(default=0, verbose_name='Bepul mocklar')),
                ('premium_mocks', models.PositiveIntegerField(default=0, verbose_name='Premium mocklar')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('subject', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='cert_subject', to='tests_app.subject', verbose_name='Fan')),
            ],
            options={
                'verbose_name': 'Sertifikat Fani',
                'verbose_name_plural': 'Sertifikat Fanlari',
                'ordering': ['order', 'subject__name'],
            },
        ),
        migrations.AddField(
            model_name='certmock',
            name='cert_subject',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='mocks', to='certificate.certsubject', verbose_name='Fan'),
        ),
        migrations.CreateModel(
            name='CertAttemptAnswer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text_answer', models.TextField(blank=True, verbose_name='Matnli javob')),
                ('structured_answer', models.JSONField(blank=True, null=True, verbose_name='Tuzilgan javob')),
                ('is_correct', models.BooleanField(blank=True, null=True, verbose_name="To'g'ri")),
                ('is_skipped', models.BooleanField(default=False, verbose_name="O'tkazildi")),
                ('earned_points', models.FloatField(default=0, verbose_name='Olingan ball')),
                ('requires_manual_check', models.BooleanField(default=False, verbose_name="Qo'lda tekshirish")),
                ('checked_at', models.DateTimeField(blank=True, null=True, verbose_name='Tekshirilgan')),
                ('answered_at', models.DateTimeField(auto_now=True, verbose_name='Javob vaqti')),
                ('selected_choice', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='certificate.certchoice', verbose_name='Tanlangan variant')),
                ('attempt', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='answers', to='certificate.certmockattempt', verbose_name='Urinish')),
                ('question', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='attempt_answers', to='certificate.certquestion', verbose_name='Savol')),
            ],
            options={
                'verbose_name': 'Urinish Javobi',
                'verbose_name_plural': 'Urinish Javoblari',
                'unique_together': {('attempt', 'question')},
            },
        ),
        migrations.AlterUniqueTogether(
            name='certmock',
            unique_together={('cert_subject', 'slug')},
        ),
    ]
