# Generated by Django 5.2.10 on 2026-03-12 11:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('certificate', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='certmock',
            name='passing_score',
        ),
        migrations.RemoveField(
            model_name='certquestion',
            name='difficulty',
        ),
    ]
