# Generated by Django 5.2.10 on 2026-03-14 06:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('certificate', '0002_remove_certmock_passing_score_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='certgroupeditem',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='cert/grouped_items/', verbose_name='Rasm'),
        ),
    ]
