# Generated by Django 5.2.10 on 2026-03-14 09:12

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('certificate', '0003_grouped_item_image'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='certquestion',
            name='difficulty',
            field=models.CharField(choices=[('easy', 'Oson'), ('medium', "O'rta"), ('hard', 'Qiyin')], default='medium', max_length=10, verbose_name='Qiyinlik'),
        ),
        migrations.AddField(
            model_name='certquestion',
            name='times_answered',
            field=models.PositiveIntegerField(default=0, verbose_name='Javob berilgan'),
        ),
        migrations.AddField(
            model_name='certquestion',
            name='times_correct',
            field=models.PositiveIntegerField(default=0, verbose_name="To'g'ri javoblar"),
        ),
        migrations.AlterField(
            model_name='certmockattempt',
            name='grade',
            field=models.CharField(blank=True, choices=[('A+', 'A+ — 70 ball va undan yuqori'), ('A', 'A — 65–69.9'), ('B+', 'B+ — 60–64.9'), ('B', 'B — 55–59.9'), ('C+', 'C+ — 50–54.9'), ('C', 'C — 46–49.9'), ('', "Sertifikat yo'q (45 va pastda)")], max_length=2, verbose_name='Baho'),
        ),
        migrations.CreateModel(
            name='CertSavedQuestion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('note', models.TextField(blank=True, verbose_name='Eslatma')),
                ('saved_at', models.DateTimeField(auto_now_add=True)),
                ('question', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='saved_by', to='certificate.certquestion', verbose_name='Savol')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cert_saved_questions', to=settings.AUTH_USER_MODEL, verbose_name='Foydalanuvchi')),
            ],
            options={
                'verbose_name': 'Saqlangan savol',
                'verbose_name_plural': 'Saqlangan savollar',
                'ordering': ['-saved_at'],
                'unique_together': {('user', 'question')},
            },
        ),
    ]
