# Generated by Django 5.2.10 on 2026-01-21 06:49

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='SubscriptionPlan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Nomi')),
                ('slug', models.SlugField(unique=True, verbose_name='Slug')),
                ('plan_type', models.CharField(choices=[('free', 'Bepul'), ('basic', 'Basic'), ('premium', 'Premium'), ('pro', 'Pro')], default='premium', max_length=20, verbose_name='Paket turi')),
                ('price', models.PositiveIntegerField(default=0, verbose_name="Narxi (so'm)")),
                ('original_price', models.PositiveIntegerField(blank=True, null=True, verbose_name='Asl narxi (chegirma uchun)')),
                ('duration_days', models.PositiveIntegerField(choices=[(7, '1 hafta'), (30, '1 oy'), (90, '3 oy'), (180, '6 oy'), (365, '1 yil')], default=30, verbose_name='Muddat (kun)')),
                ('features', models.JSONField(default=list, verbose_name='Imkoniyatlar')),
                ('daily_test_limit', models.PositiveIntegerField(blank=True, help_text='NULL = cheksiz', null=True, verbose_name='Kunlik test limiti')),
                ('daily_ai_chat_limit', models.PositiveIntegerField(blank=True, null=True, verbose_name='Kunlik AI chat limiti')),
                ('can_access_analytics', models.BooleanField(default=False, verbose_name='Tahlil sahifasi')),
                ('can_access_ai_mentor', models.BooleanField(default=False, verbose_name='AI Mentor')),
                ('can_download_pdf', models.BooleanField(default=False, verbose_name='PDF yuklab olish')),
                ('can_access_competitions', models.BooleanField(default=True, verbose_name='Musobaqalar')),
                ('ad_free', models.BooleanField(default=False, verbose_name="Reklama yo'q")),
                ('is_active', models.BooleanField(default=True, verbose_name='Faol')),
                ('is_featured', models.BooleanField(default=False, verbose_name='Tavsiya etilgan')),
                ('order', models.PositiveIntegerField(default=0, verbose_name='Tartib')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Obuna paketi',
                'verbose_name_plural': 'Obuna paketlari',
                'ordering': ['order', 'price'],
            },
        ),
        migrations.CreateModel(
            name='Subscription',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('status', models.CharField(choices=[('active', 'Faol'), ('expired', 'Muddati tugagan'), ('cancelled', 'Bekor qilingan'), ('pending', 'Kutilmoqda')], default='pending', max_length=20, verbose_name='Holat')),
                ('started_at', models.DateTimeField(blank=True, null=True, verbose_name='Boshlangan')),
                ('expires_at', models.DateTimeField(blank=True, null=True, verbose_name='Tugash vaqti')),
                ('cancelled_at', models.DateTimeField(blank=True, null=True, verbose_name='Bekor qilingan')),
                ('auto_renew', models.BooleanField(default=False, verbose_name='Avtomatik uzaytirish')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='subscriptions', to=settings.AUTH_USER_MODEL)),
                ('plan', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='subscriptions', to='subscriptions.subscriptionplan')),
            ],
            options={
                'verbose_name': 'Obuna',
                'verbose_name_plural': 'Obunalar',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='PromoCode',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(db_index=True, max_length=50, unique=True, verbose_name='Kod')),
                ('description', models.TextField(blank=True, verbose_name='Tavsif')),
                ('discount_type', models.CharField(choices=[('percent', 'Foiz'), ('fixed', "Qat'iy summa"), ('free_days', 'Bepul kunlar')], max_length=20, verbose_name='Chegirma turi')),
                ('discount_value', models.PositiveIntegerField(verbose_name='Chegirma qiymati')),
                ('max_uses', models.PositiveIntegerField(blank=True, null=True, verbose_name='Maksimum ishlatish')),
                ('max_uses_per_user', models.PositiveIntegerField(default=1, verbose_name='Har bir user uchun max')),
                ('current_uses', models.PositiveIntegerField(default=0, verbose_name='Hozirgi ishlatishlar')),
                ('valid_from', models.DateTimeField(verbose_name='Boshlanish vaqti')),
                ('valid_until', models.DateTimeField(verbose_name='Tugash vaqti')),
                ('is_active', models.BooleanField(default=True, verbose_name='Faol')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('plan', models.ForeignKey(blank=True, help_text='Faqat shu paket uchun', null=True, on_delete=django.db.models.deletion.SET_NULL, to='subscriptions.subscriptionplan')),
            ],
            options={
                'verbose_name': 'Promo kod',
                'verbose_name_plural': 'Promo kodlar',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Payment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('order_id', models.CharField(max_length=50, unique=True, verbose_name='Buyurtma ID')),
                ('amount', models.PositiveIntegerField(verbose_name="Summa (so'm)")),
                ('provider', models.CharField(choices=[('click', 'Click'), ('payme', 'Payme'), ('uzum', 'Uzum Bank'), ('manual', "Qo'lda"), ('promo', 'Promo kod')], max_length=20, verbose_name="To'lov tizimi")),
                ('status', models.CharField(choices=[('pending', 'Kutilmoqda'), ('processing', 'Jarayonda'), ('completed', 'Muvaffaqiyatli'), ('failed', 'Muvaffaqiyatsiz'), ('cancelled', 'Bekor qilingan'), ('refunded', 'Qaytarilgan')], default='pending', max_length=20, verbose_name='Holat')),
                ('provider_transaction_id', models.CharField(blank=True, max_length=100, verbose_name='Provider transaction ID')),
                ('provider_response', models.JSONField(blank=True, default=dict, verbose_name='Provider javobi')),
                ('description', models.TextField(blank=True, verbose_name='Tavsif')),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True, verbose_name='IP manzil')),
                ('user_agent', models.TextField(blank=True, verbose_name='User Agent')),
                ('paid_at', models.DateTimeField(blank=True, null=True, verbose_name="To'langan vaqt")),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='payments', to=settings.AUTH_USER_MODEL)),
                ('subscription', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='payments', to='subscriptions.subscription')),
                ('plan', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='payments', to='subscriptions.subscriptionplan')),
            ],
            options={
                'verbose_name': "To'lov",
                'verbose_name_plural': "To'lovlar",
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='UserDailyLimit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(verbose_name='Sana')),
                ('tests_taken', models.PositiveIntegerField(default=0, verbose_name='Yechilgan testlar')),
                ('ai_chats_used', models.PositiveIntegerField(default=0, verbose_name='AI chat ishlatilgan')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Kunlik limit',
                'verbose_name_plural': 'Kunlik limitlar',
            },
        ),
        migrations.CreateModel(
            name='PromoCodeUsage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('discount_amount', models.PositiveIntegerField(verbose_name='Chegirma summasi')),
                ('used_at', models.DateTimeField(auto_now_add=True)),
                ('payment', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='subscriptions.payment')),
                ('promo_code', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='usages', to='subscriptions.promocode')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Promo kod ishlatish',
                'verbose_name_plural': 'Promo kod ishlatishlar',
                'unique_together': {('promo_code', 'user', 'payment')},
            },
        ),
        migrations.AddIndex(
            model_name='payment',
            index=models.Index(fields=['order_id'], name='subscriptio_order_i_4a6d6c_idx'),
        ),
        migrations.AddIndex(
            model_name='payment',
            index=models.Index(fields=['user', 'status'], name='subscriptio_user_id_9c57a2_idx'),
        ),
        migrations.AddIndex(
            model_name='payment',
            index=models.Index(fields=['provider', 'status'], name='subscriptio_provide_eb62c5_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='userdailylimit',
            unique_together={('user', 'date')},
        ),
    ]
