# Generated by Django 5.2.1 on 2026-02-20 11:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('subscriptions', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='payment',
            name='admin_note',
            field=models.TextField(blank=True, verbose_name='Admin eslatmasi'),
        ),
        migrations.AddField(
            model_name='payment',
            name='receipt_image',
            field=models.ImageField(blank=True, null=True, upload_to='receipts/%Y/%m/', verbose_name='Chek rasmi'),
        ),
    ]
