# Generated by Django 5.2.10 on 2026-03-02 04:36

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('subscriptions', '0003_seed_subscription_plans'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='FeatureTrialUsage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('feature', models.CharField(choices=[('study_plan', "O'quv reja"), ('wrong_answers', 'Xato javoblar'), ('behavioral_insights', 'Xulq tahlili'), ('university_dashboard', 'Universitetlar')], max_length=50)),
                ('usage_count', models.PositiveIntegerField(default=0)),
                ('first_used_at', models.DateTimeField(auto_now_add=True)),
                ('last_used_at', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='feature_trials', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Sinov foydalanish',
                'verbose_name_plural': 'Sinov foydalanishlar',
                'unique_together': {('user', 'feature')},
            },
        ),
    ]
