# Generated by Django 5.2.10 on 2026-01-19 05:11

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('tests_app', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Battle',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('is_block_test', models.BooleanField(default=False, verbose_name='Blok test')),
                ('question_count', models.PositiveIntegerField(default=10, verbose_name='Savollar soni')),
                ('time_per_question', models.PositiveIntegerField(default=30, verbose_name='Savol uchun vaqt (soniya)')),
                ('questions_data', models.JSONField(default=list, verbose_name='Savollar')),
                ('status', models.CharField(choices=[('pending', 'Kutilmoqda'), ('accepted', 'Qabul qilingan'), ('in_progress', 'Davom etmoqda'), ('completed', 'Yakunlangan'), ('rejected', 'Rad etilgan'), ('expired', "Muddati o'tgan")], default='pending', max_length=20, verbose_name='Holat')),
                ('challenger_score', models.PositiveIntegerField(default=0, verbose_name='Chaqiruvchi bali')),
                ('challenger_correct', models.PositiveIntegerField(default=0, verbose_name="Chaqiruvchi to'g'ri")),
                ('challenger_time', models.PositiveIntegerField(default=0, verbose_name='Chaqiruvchi vaqti')),
                ('challenger_answers', models.JSONField(default=list, verbose_name='Chaqiruvchi javoblari')),
                ('challenger_completed', models.BooleanField(default=False, verbose_name='Chaqiruvchi yakunladi')),
                ('opponent_score', models.PositiveIntegerField(default=0, verbose_name='Raqib bali')),
                ('opponent_correct', models.PositiveIntegerField(default=0, verbose_name="Raqib to'g'ri")),
                ('opponent_time', models.PositiveIntegerField(default=0, verbose_name='Raqib vaqti')),
                ('opponent_answers', models.JSONField(default=list, verbose_name='Raqib javoblari')),
                ('opponent_completed', models.BooleanField(default=False, verbose_name='Raqib yakunladi')),
                ('is_draw', models.BooleanField(default=False, verbose_name='Durrang')),
                ('winner_xp', models.PositiveIntegerField(default=50, verbose_name="G'olib XP")),
                ('loser_xp', models.PositiveIntegerField(default=10, verbose_name='Yutqazuvchi XP')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('accepted_at', models.DateTimeField(blank=True, null=True, verbose_name='Qabul qilingan')),
                ('started_at', models.DateTimeField(blank=True, null=True, verbose_name='Boshlangan')),
                ('completed_at', models.DateTimeField(blank=True, null=True, verbose_name='Yakunlangan')),
                ('expires_at', models.DateTimeField(verbose_name='Amal qilish muddati')),
                ('challenger', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='battles_challenged', to=settings.AUTH_USER_MODEL, verbose_name='Chaqiruvchi')),
                ('opponent', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='battles_received', to=settings.AUTH_USER_MODEL, verbose_name='Raqib')),
                ('subject', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='battles', to='tests_app.subject', verbose_name='Fan')),
                ('winner', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='battles_won', to=settings.AUTH_USER_MODEL, verbose_name="G'olib")),
            ],
            options={
                'verbose_name': 'Jang',
                'verbose_name_plural': 'Janglar',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='BattleInvitation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sent_at', models.DateTimeField(auto_now_add=True)),
                ('seen_at', models.DateTimeField(blank=True, null=True)),
                ('responded_at', models.DateTimeField(blank=True, null=True)),
                ('battle', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='invitations', to='competitions.battle')),
            ],
            options={
                'verbose_name': 'Jang taklifi',
                'verbose_name_plural': 'Jang takliflari',
            },
        ),
        migrations.CreateModel(
            name='Competition',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('title', models.CharField(max_length=200, verbose_name='Sarlavha')),
                ('slug', models.SlugField(unique=True, verbose_name='Slug')),
                ('description', models.TextField(verbose_name='Tavsif')),
                ('rules', models.TextField(blank=True, verbose_name='Qoidalar')),
                ('competition_type', models.CharField(choices=[('daily', 'Kunlik'), ('weekly', 'Haftalik'), ('monthly', 'Oylik'), ('special', 'Maxsus'), ('olympiad', 'Olimpiada')], default='weekly', max_length=20, verbose_name='Turi')),
                ('status', models.CharField(choices=[('upcoming', 'Kutilmoqda'), ('active', 'Faol'), ('finished', 'Yakunlangan'), ('cancelled', 'Bekor qilingan')], default='upcoming', max_length=20, verbose_name='Holat')),
                ('banner', models.ImageField(blank=True, null=True, upload_to='competitions/banners/', verbose_name='Banner')),
                ('start_time', models.DateTimeField(verbose_name='Boshlanish vaqti')),
                ('end_time', models.DateTimeField(verbose_name='Tugash vaqti')),
                ('duration_minutes', models.PositiveIntegerField(default=60, verbose_name='Davomiyligi (daqiqa)')),
                ('max_participants', models.PositiveIntegerField(blank=True, null=True, verbose_name='Max qatnashchilar')),
                ('min_level', models.CharField(blank=True, max_length=20, verbose_name='Min daraja')),
                ('is_premium_only', models.BooleanField(default=False, verbose_name='Faqat Premium')),
                ('prizes', models.JSONField(blank=True, default=list, verbose_name='Sovrinlar')),
                ('xp_reward_first', models.PositiveIntegerField(default=500, verbose_name="1-o'rin XP")),
                ('xp_reward_second', models.PositiveIntegerField(default=300, verbose_name="2-o'rin XP")),
                ('xp_reward_third', models.PositiveIntegerField(default=100, verbose_name="3-o'rin XP")),
                ('xp_participation', models.PositiveIntegerField(default=20, verbose_name='Qatnashish XP')),
                ('participants_count', models.PositiveIntegerField(default=0, verbose_name='Qatnashchilar soni')),
                ('is_active', models.BooleanField(default=True, verbose_name='Faol')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_competitions', to=settings.AUTH_USER_MODEL)),
                ('subject', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='competitions', to='tests_app.subject', verbose_name='Fan')),
                ('test', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='competitions', to='tests_app.test', verbose_name='Test')),
            ],
            options={
                'verbose_name': 'Musobaqa',
                'verbose_name_plural': 'Musobaqalar',
                'ordering': ['-start_time'],
            },
        ),
        migrations.CreateModel(
            name='DailyChallenge',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(unique=True, verbose_name='Sana')),
                ('xp_reward', models.PositiveIntegerField(default=100, verbose_name='XP mukofot')),
                ('participants_count', models.PositiveIntegerField(default=0, verbose_name='Qatnashchilar')),
                ('is_active', models.BooleanField(default=True, verbose_name='Faol')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('questions', models.ManyToManyField(related_name='daily_challenges', to='tests_app.question')),
                ('subject', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='daily_challenges', to='tests_app.subject')),
            ],
            options={
                'verbose_name': 'Kunlik challenge',
                'verbose_name_plural': 'Kunlik challengelar',
                'ordering': ['-date'],
            },
        ),
        migrations.CreateModel(
            name='CompetitionParticipant',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('score', models.FloatField(default=0, verbose_name='Ball')),
                ('correct_answers', models.PositiveIntegerField(default=0, verbose_name="To'g'ri javoblar")),
                ('wrong_answers', models.PositiveIntegerField(default=0, verbose_name="Noto'g'ri javoblar")),
                ('time_spent', models.PositiveIntegerField(default=0, verbose_name='Sarflangan vaqt (soniya)')),
                ('rank', models.PositiveIntegerField(blank=True, null=True, verbose_name="O'rin")),
                ('xp_earned', models.PositiveIntegerField(default=0, verbose_name='Olingan XP')),
                ('is_started', models.BooleanField(default=False, verbose_name='Boshlangan')),
                ('is_completed', models.BooleanField(default=False, verbose_name='Yakunlangan')),
                ('started_at', models.DateTimeField(blank=True, null=True, verbose_name='Boshlangan vaqt')),
                ('completed_at', models.DateTimeField(blank=True, null=True, verbose_name='Yakunlangan vaqt')),
                ('joined_at', models.DateTimeField(auto_now_add=True, verbose_name="Qo'shilgan vaqt")),
                ('competition', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='participants', to='competitions.competition', verbose_name='Musobaqa')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='competition_participations', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Qatnashchi',
                'verbose_name_plural': 'Qatnashchilar',
                'ordering': ['rank', '-score'],
                'unique_together': {('competition', 'user')},
            },
        ),
        migrations.CreateModel(
            name='DailyChallengeParticipant',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('score', models.PositiveIntegerField(default=0, verbose_name='Ball')),
                ('correct_answers', models.PositiveIntegerField(default=0, verbose_name="To'g'ri")),
                ('time_spent', models.PositiveIntegerField(default=0, verbose_name='Vaqt (soniya)')),
                ('xp_earned', models.PositiveIntegerField(default=0, verbose_name='Olingan XP')),
                ('completed_at', models.DateTimeField(auto_now_add=True)),
                ('challenge', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='participants', to='competitions.dailychallenge')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='daily_challenges', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Challenge qatnashchisi',
                'verbose_name_plural': 'Challenge qatnashchilari',
                'ordering': ['-score', 'time_spent'],
                'unique_together': {('challenge', 'user')},
            },
        ),
    ]
