# Generated by Django 5.2.10 on 2026-01-28 17:40

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('competitions', '0001_initial'),
        ('tests_app', '0002_useranalyticssummary_userstudysession_dailyuserstats_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='WeeklyLeague',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('week_start', models.DateField(verbose_name='Hafta boshlanishi')),
                ('week_end', models.DateField(verbose_name='Hafta tugashi')),
                ('tier', models.CharField(choices=[('bronze', 'Bronza'), ('silver', 'Kumush'), ('gold', 'Oltin'), ('platinum', 'Platina'), ('diamond', 'Olmos'), ('master', 'Master'), ('grandmaster', 'Grandmaster')], default='bronze', max_length=20, verbose_name='Daraja')),
                ('xp_reward_first', models.PositiveIntegerField(default=300, verbose_name="1-o'rin XP")),
                ('xp_reward_top3', models.PositiveIntegerField(default=200, verbose_name='Top 3 XP')),
                ('xp_reward_top10', models.PositiveIntegerField(default=100, verbose_name='Top 10 XP')),
                ('promotion_count', models.PositiveIntegerField(default=3, verbose_name="Ko'tarilish soni")),
                ('demotion_count', models.PositiveIntegerField(default=3, verbose_name='Tushish soni')),
                ('is_active', models.BooleanField(default=True, verbose_name='Faol')),
                ('is_processed', models.BooleanField(default=False, verbose_name='Hisoblangan')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Haftalik liga',
                'verbose_name_plural': 'Haftalik ligalar',
                'ordering': ['-week_start', 'tier'],
            },
        ),
        migrations.AlterModelOptions(
            name='competitionparticipant',
            options={'ordering': ['rank', '-score', 'time_spent'], 'verbose_name': 'Qatnashchi', 'verbose_name_plural': 'Qatnashchilar'},
        ),
        migrations.RemoveField(
            model_name='battle',
            name='is_block_test',
        ),
        migrations.RemoveField(
            model_name='competition',
            name='is_premium_only',
        ),
        migrations.RemoveField(
            model_name='competitionparticipant',
            name='is_completed',
        ),
        migrations.RemoveField(
            model_name='competitionparticipant',
            name='is_started',
        ),
        migrations.AddField(
            model_name='battle',
            name='bot_difficulty',
            field=models.CharField(blank=True, choices=[('easy', 'Oson'), ('medium', "O'rta"), ('hard', 'Qiyin'), ('expert', 'Ekspert')], max_length=10, verbose_name='Bot qiyinligi'),
        ),
        migrations.AddField(
            model_name='battle',
            name='is_dtm_format',
            field=models.BooleanField(default=False, verbose_name='DTM formati'),
        ),
        migrations.AddField(
            model_name='battle',
            name='opponent_type',
            field=models.CharField(choices=[('friend', "Do'st"), ('random', 'Random'), ('bot', 'Bot')], default='friend', max_length=10, verbose_name='Raqib turi'),
        ),
        migrations.AddField(
            model_name='battle',
            name='total_time',
            field=models.PositiveIntegerField(default=300, verbose_name='Jami vaqt (soniya)'),
        ),
        migrations.AddField(
            model_name='battle',
            name='winner_is_bot',
            field=models.BooleanField(default=False, verbose_name='Bot yutdi'),
        ),
        migrations.AddField(
            model_name='battle',
            name='xp_awarded',
            field=models.BooleanField(default=False, verbose_name='XP berildi'),
        ),
        migrations.AddField(
            model_name='battleinvitation',
            name='notification_sent',
            field=models.BooleanField(default=False, verbose_name='Xabar yuborildi'),
        ),
        migrations.AddField(
            model_name='competition',
            name='allow_review',
            field=models.BooleanField(default=True, verbose_name='Tahlil qilishga ruxsat'),
        ),
        migrations.AddField(
            model_name='competition',
            name='anti_cheat_enabled',
            field=models.BooleanField(default=True, verbose_name='Anti-cheat yoqish'),
        ),
        migrations.AddField(
            model_name='competition',
            name='average_score',
            field=models.FloatField(default=0, verbose_name="O'rtacha ball"),
        ),
        migrations.AddField(
            model_name='competition',
            name='certificate_enabled',
            field=models.BooleanField(default=False, verbose_name='Sertifikat berish'),
        ),
        migrations.AddField(
            model_name='competition',
            name='completed_count',
            field=models.PositiveIntegerField(default=0, verbose_name='Yakunlaganlar soni'),
        ),
        migrations.AddField(
            model_name='competition',
            name='difficulty_distribution',
            field=models.JSONField(blank=True, default=dict, help_text='{"easy": 30, "medium": 50, "hard": 20}', verbose_name='Qiyinlik taqsimoti'),
        ),
        migrations.AddField(
            model_name='competition',
            name='entry_fee',
            field=models.PositiveIntegerField(default=0, verbose_name="Kirish narxi (so'm)"),
        ),
        migrations.AddField(
            model_name='competition',
            name='entry_type',
            field=models.CharField(choices=[('free', 'Bepul'), ('premium_only', 'Faqat Premium'), ('paid', 'Pullik')], default='free', max_length=20, verbose_name='Kirish turi'),
        ),
        migrations.AddField(
            model_name='competition',
            name='icon',
            field=models.CharField(default='🏆', max_length=10, verbose_name='Icon (emoji)'),
        ),
        migrations.AddField(
            model_name='competition',
            name='is_featured',
            field=models.BooleanField(default=False, verbose_name='Tanlanganlar'),
        ),
        migrations.AddField(
            model_name='competition',
            name='min_participants',
            field=models.PositiveIntegerField(default=1, verbose_name='Min qatnashchilar'),
        ),
        migrations.AddField(
            model_name='competition',
            name='min_rating',
            field=models.PositiveIntegerField(default=0, verbose_name='Min reyting'),
        ),
        migrations.AddField(
            model_name='competition',
            name='prize_pool',
            field=models.PositiveIntegerField(default=0, verbose_name="Sovrin fondi (so'm)"),
        ),
        migrations.AddField(
            model_name='competition',
            name='questions_per_subject',
            field=models.PositiveIntegerField(default=30, verbose_name='Har fandan savollar'),
        ),
        migrations.AddField(
            model_name='competition',
            name='registration_end',
            field=models.DateTimeField(blank=True, null=True, verbose_name="Ro'yxat tugashi"),
        ),
        migrations.AddField(
            model_name='competition',
            name='registration_start',
            field=models.DateTimeField(blank=True, null=True, verbose_name="Ro'yxat boshlanishi"),
        ),
        migrations.AddField(
            model_name='competition',
            name='short_description',
            field=models.CharField(blank=True, max_length=300, verbose_name='Qisqa tavsif'),
        ),
        migrations.AddField(
            model_name='competition',
            name='show_answers_after',
            field=models.BooleanField(default=True, verbose_name="Javoblarni ko'rsatish"),
        ),
        migrations.AddField(
            model_name='competition',
            name='show_live_leaderboard',
            field=models.BooleanField(default=True, verbose_name="Live reyting ko'rsatish"),
        ),
        migrations.AddField(
            model_name='competition',
            name='sponsors',
            field=models.JSONField(blank=True, default=list, help_text='[{"name": "...", "logo": "...", "url": "..."}]', verbose_name='Homiylar'),
        ),
        migrations.AddField(
            model_name='competition',
            name='subjects',
            field=models.ManyToManyField(blank=True, related_name='multi_competitions', to='tests_app.subject', verbose_name='Fanlar (DTM blok)'),
        ),
        migrations.AddField(
            model_name='competition',
            name='test_format',
            field=models.CharField(choices=[('single_subject', 'Bitta fan'), ('multi_subject', "Ko'p fan"), ('dtm_block', 'DTM blok')], default='single_subject', max_length=20, verbose_name='Test formati'),
        ),
        migrations.AddField(
            model_name='competition',
            name='total_questions',
            field=models.PositiveIntegerField(default=30, verbose_name='Jami savollar'),
        ),
        migrations.AddField(
            model_name='competition',
            name='xp_per_correct',
            field=models.PositiveIntegerField(default=5, verbose_name="To'g'ri javob XP"),
        ),
        migrations.AddField(
            model_name='competitionparticipant',
            name='answers_data',
            field=models.JSONField(blank=True, default=list, verbose_name='Javoblar'),
        ),
        migrations.AddField(
            model_name='competitionparticipant',
            name='is_suspected',
            field=models.BooleanField(default=False, verbose_name='Shubhali'),
        ),
        migrations.AddField(
            model_name='competitionparticipant',
            name='percentage',
            field=models.FloatField(default=0, verbose_name='Foiz'),
        ),
        migrations.AddField(
            model_name='competitionparticipant',
            name='prize_amount',
            field=models.PositiveIntegerField(default=0, verbose_name="Sovrin (so'm)"),
        ),
        migrations.AddField(
            model_name='competitionparticipant',
            name='skipped_answers',
            field=models.PositiveIntegerField(default=0, verbose_name="O'tkazib yuborilgan"),
        ),
        migrations.AddField(
            model_name='competitionparticipant',
            name='status',
            field=models.CharField(choices=[('registered', "Ro'yxatdan o'tgan"), ('ready', 'Tayyor'), ('in_progress', 'Davom etmoqda'), ('completed', 'Yakunlagan'), ('disqualified', 'Diskvalifikatsiya')], default='registered', max_length=20, verbose_name='Holat'),
        ),
        migrations.AddField(
            model_name='competitionparticipant',
            name='violations_count',
            field=models.PositiveIntegerField(default=0, verbose_name='Qoidabuzarlik soni'),
        ),
        migrations.AddField(
            model_name='competitionparticipant',
            name='violations_log',
            field=models.JSONField(blank=True, default=list, verbose_name='Qoidabuzarlik logi'),
        ),
        migrations.AddField(
            model_name='dailychallenge',
            name='average_score',
            field=models.FloatField(default=0, verbose_name="O'rtacha ball"),
        ),
        migrations.AddField(
            model_name='dailychallenge',
            name='bonus_xp_top10',
            field=models.PositiveIntegerField(default=50, verbose_name='Top 10 bonus XP'),
        ),
        migrations.AddField(
            model_name='dailychallenge',
            name='question_count',
            field=models.PositiveIntegerField(default=10, verbose_name='Savollar soni'),
        ),
        migrations.AddField(
            model_name='dailychallenge',
            name='time_limit',
            field=models.PositiveIntegerField(default=15, verbose_name='Vaqt limiti (daqiqa)'),
        ),
        migrations.AddField(
            model_name='dailychallengeparticipant',
            name='answers_data',
            field=models.JSONField(blank=True, default=list, verbose_name='Javoblar'),
        ),
        migrations.AddField(
            model_name='dailychallengeparticipant',
            name='percentage',
            field=models.FloatField(default=0, verbose_name='Foiz'),
        ),
        migrations.AddField(
            model_name='dailychallengeparticipant',
            name='rank',
            field=models.PositiveIntegerField(blank=True, null=True, verbose_name="O'rin"),
        ),
        migrations.AddField(
            model_name='dailychallengeparticipant',
            name='wrong_answers',
            field=models.PositiveIntegerField(default=0, verbose_name="Noto'g'ri"),
        ),
        migrations.AlterField(
            model_name='battle',
            name='opponent',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='battles_received', to=settings.AUTH_USER_MODEL, verbose_name='Raqib'),
        ),
        migrations.AlterField(
            model_name='battle',
            name='status',
            field=models.CharField(choices=[('pending', 'Kutilmoqda'), ('searching', 'Raqib qidirilmoqda'), ('accepted', 'Qabul qilingan'), ('in_progress', 'Davom etmoqda'), ('completed', 'Yakunlangan'), ('rejected', 'Rad etilgan'), ('expired', "Muddati o'tgan"), ('cancelled', 'Bekor qilingan')], default='pending', max_length=20, verbose_name='Holat'),
        ),
        migrations.AlterField(
            model_name='competition',
            name='competition_type',
            field=models.CharField(choices=[('daily', 'Kunlik'), ('weekly', 'Haftalik'), ('monthly', 'Oylik'), ('special', 'Maxsus'), ('olympiad', 'Olimpiada'), ('tournament', 'Turnir')], default='weekly', max_length=20, verbose_name='Turi'),
        ),
        migrations.AlterField(
            model_name='competition',
            name='min_level',
            field=models.PositiveIntegerField(default=0, verbose_name='Min daraja'),
        ),
        migrations.AlterField(
            model_name='competition',
            name='prizes',
            field=models.JSONField(blank=True, default=list, help_text='[{"place": 1, "amount": 500000, "description": "1-o\'rin"}, ...]', verbose_name='Sovrinlar'),
        ),
        migrations.AlterField(
            model_name='competition',
            name='status',
            field=models.CharField(choices=[('draft', 'Qoralama'), ('upcoming', 'Kutilmoqda'), ('registration', "Ro'yxatdan o'tish"), ('active', 'Faol'), ('finished', 'Yakunlangan'), ('cancelled', 'Bekor qilingan')], default='draft', max_length=20, verbose_name='Holat'),
        ),
        migrations.AlterField(
            model_name='dailychallengeparticipant',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='daily_challenge_participations', to=settings.AUTH_USER_MODEL),
        ),
        migrations.CreateModel(
            name='CompetitionPayment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('amount', models.PositiveIntegerField(verbose_name="Summa (so'm)")),
                ('status', models.CharField(choices=[('pending', 'Kutilmoqda'), ('completed', "To'langan"), ('failed', 'Muvaffaqiyatsiz'), ('refunded', 'Qaytarilgan')], default='pending', max_length=20, verbose_name='Holat')),
                ('payment_method', models.CharField(blank=True, max_length=50, verbose_name="To'lov usuli")),
                ('transaction_id', models.CharField(blank=True, max_length=100, verbose_name='Tranzaksiya ID')),
                ('paid_at', models.DateTimeField(blank=True, null=True, verbose_name="To'langan vaqt")),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('participant', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='payment', to='competitions.competitionparticipant')),
            ],
            options={
                'verbose_name': "To'lov",
                'verbose_name_plural': "To'lovlar",
            },
        ),
        migrations.CreateModel(
            name='MatchmakingQueue',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_rating', models.PositiveIntegerField(default=1000, verbose_name='Reyting')),
                ('user_level', models.PositiveIntegerField(default=1, verbose_name='Daraja')),
                ('question_count', models.PositiveIntegerField(default=10, verbose_name='Savollar soni')),
                ('rating_range', models.PositiveIntegerField(default=200, verbose_name="Reyting oralig'i")),
                ('joined_at', models.DateTimeField(auto_now_add=True)),
                ('expires_at', models.DateTimeField(verbose_name='Muddati')),
                ('is_matched', models.BooleanField(default=False, verbose_name='Topildi')),
                ('battle', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='competitions.battle')),
                ('matched_with', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='matched_by', to=settings.AUTH_USER_MODEL)),
                ('subject', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='tests_app.subject')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='matchmaking_queue', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Matchmaking navbat',
                'verbose_name_plural': 'Matchmaking navbatlar',
            },
        ),
        migrations.CreateModel(
            name='Certificate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('certificate_type', models.CharField(choices=[('participation', 'Ishtirok sertifikati'), ('winner', "G'olib sertifikati"), ('top3', 'Top 3 sertifikati'), ('top10', 'Top 10 sertifikati')], default='participation', max_length=20, verbose_name='Turi')),
                ('rank', models.PositiveIntegerField(blank=True, null=True, verbose_name="O'rin")),
                ('score', models.FloatField(default=0, verbose_name='Ball')),
                ('file', models.FileField(blank=True, null=True, upload_to='certificates/', verbose_name='Fayl')),
                ('issued_at', models.DateTimeField(auto_now_add=True, verbose_name='Berilgan vaqt')),
                ('verification_code', models.CharField(max_length=20, unique=True, verbose_name='Tasdiqlash kodi')),
                ('is_verified', models.BooleanField(default=True, verbose_name='Tasdiqlangan')),
                ('competition', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='certificates', to='competitions.competition')),
                ('participant', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='certificate', to='competitions.competitionparticipant')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='certificates', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Sertifikat',
                'verbose_name_plural': 'Sertifikatlar',
                'unique_together': {('user', 'competition')},
            },
        ),
        migrations.CreateModel(
            name='WeeklyLeagueParticipant',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('xp_earned', models.PositiveIntegerField(default=0, verbose_name="Yig'ilgan XP")),
                ('tests_completed', models.PositiveIntegerField(default=0, verbose_name='Testlar')),
                ('correct_answers', models.PositiveIntegerField(default=0, verbose_name="To'g'ri javoblar")),
                ('rank', models.PositiveIntegerField(blank=True, null=True, verbose_name="O'rin")),
                ('is_promoted', models.BooleanField(default=False, verbose_name="Ko'tarildi")),
                ('is_demoted', models.BooleanField(default=False, verbose_name='Tushdi')),
                ('joined_at', models.DateTimeField(auto_now_add=True)),
                ('league', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='participants', to='competitions.weeklyleague')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='weekly_leagues', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Liga qatnashchisi',
                'verbose_name_plural': 'Liga qatnashchilari',
                'ordering': ['rank', '-xp_earned'],
                'unique_together': {('league', 'user')},
            },
        ),
    ]
