# Generated by Django 5.2.10 on 2026-02-14 03:21

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('competitions', '0002_weeklyleague_alter_competitionparticipant_options_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='battle',
            name='invite_code',
            field=models.CharField(blank=True, help_text='Havola orqali taklif uchun unikal kod', max_length=20, null=True, unique=True, verbose_name='Taklif kodi'),
        ),
        migrations.AddField(
            model_name='battleinvitation',
            name='invited_user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='battle_invitations_received', to=settings.AUTH_USER_MODEL, verbose_name='Taklif qilingan'),
        ),
        migrations.AddField(
            model_name='battleinvitation',
            name='status',
            field=models.CharField(choices=[('pending', 'Kutilmoqda'), ('accepted', 'Qabul qilingan'), ('declined', 'Rad etilgan'), ('expired', "Muddati o'tgan")], default='pending', max_length=10, verbose_name='Holat'),
        ),
        migrations.CreateModel(
            name='Friendship',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('pending', 'Kutilmoqda'), ('accepted', 'Qabul qilingan'), ('declined', 'Rad etilgan'), ('blocked', 'Bloklangan')], default='pending', max_length=10, verbose_name='Holat')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Yaratilgan')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Yangilangan')),
                ('from_user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sent_friendships', to=settings.AUTH_USER_MODEL, verbose_name='Yuboruvchi')),
                ('to_user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='received_friendships', to=settings.AUTH_USER_MODEL, verbose_name='Qabul qiluvchi')),
            ],
            options={
                'verbose_name': "Do'stlik",
                'verbose_name_plural': "Do'stliklar",
                'ordering': ['-created_at'],
                'unique_together': {('from_user', 'to_user')},
            },
        ),
    ]
