# Generated by Django 5.2.10 on 2026-02-14 09:57

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('competitions', '0003_battle_invite_code_battleinvitation_invited_user_and_more'),
        ('tests_app', '0002_useranalyticssummary_userstudysession_dailyuserstats_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='competition',
            name='question_source',
            field=models.CharField(choices=[('auto', 'Avtomatik (bankdan)'), ('manual', "Qo'lda tanlangan"), ('mixed', 'Aralash')], default='auto', help_text="Avtomatik = bankdan tasodifiy. Qo'lda = faqat tanlangan savollar.", max_length=10, verbose_name='Savol manbasi'),
        ),
        migrations.CreateModel(
            name='CompetitionQuestion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order', models.PositiveIntegerField(default=0, verbose_name='Tartib')),
                ('competition', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='competition_questions', to='competitions.competition', verbose_name='Musobaqa')),
                ('question', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='competition_assignments', to='tests_app.question', verbose_name='Savol')),
            ],
            options={
                'verbose_name': 'Musobaqa savoli',
                'verbose_name_plural': 'Musobaqa savollari',
                'ordering': ['order'],
                'unique_together': {('competition', 'question')},
            },
        ),
    ]
