# Generated by Django 5.2.10 on 2026-03-03 08:05

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('competitions', '0004_competition_question_source_competitionquestion'),
        ('tests_app', '0002_useranalyticssummary_userstudysession_dailyuserstats_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='dailychallenge',
            name='subjects',
            field=models.ManyToManyField(blank=True, help_text='Bir yoki bir nechta fan tanlang — savollar avtomatik random tanlanadi', related_name='daily_challenges_multi', to='tests_app.subject', verbose_name='Fanlar'),
        ),
        migrations.AlterField(
            model_name='competition',
            name='status',
            field=models.CharField(choices=[('draft', 'Qoralama'), ('upcoming', 'Kutilmoqda'), ('registration', "Ro'yxatdan o'tish"), ('active', 'Faol'), ('paused', "To'xtatilgan"), ('finished', 'Yakunlangan'), ('cancelled', 'Bekor qilingan')], default='draft', max_length=20, verbose_name='Holat'),
        ),
        migrations.AlterField(
            model_name='dailychallenge',
            name='questions',
            field=models.ManyToManyField(blank=True, related_name='daily_challenges', to='tests_app.question', verbose_name='Savollar (avtomatik)'),
        ),
        migrations.AlterField(
            model_name='dailychallenge',
            name='subject',
            field=models.ForeignKey(blank=True, help_text='Eski maydon — "Fanlar" ishlatiladi', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='daily_challenges', to='tests_app.subject', verbose_name='Fan (eski)'),
        ),
    ]
