# Generated by Django 5.2.10 on 2026-03-03 08:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('competitions', '0005_add_subjects_m2m_to_dailychallenge'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dailychallenge',
            name='date',
            field=models.DateField(db_index=True, verbose_name='Sana'),
        ),
    ]
