# Generated by Django 5.2.10 on 2026-01-19 05:11

import django.core.validators
import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('tests_app', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Faculty',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='Nomi')),
                ('slug', models.SlugField(verbose_name='Slug')),
                ('description', models.TextField(blank=True, verbose_name='Tavsif')),
                ('is_active', models.BooleanField(default=True, verbose_name='Faol')),
            ],
            options={
                'verbose_name': 'Fakultet',
                'verbose_name_plural': 'Fakultetlar',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='University',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('name', models.CharField(max_length=300, verbose_name='Nomi')),
                ('short_name', models.CharField(blank=True, max_length=50, verbose_name='Qisqa nomi')),
                ('slug', models.SlugField(unique=True, verbose_name='Slug')),
                ('university_type', models.CharField(choices=[('state', 'Davlat'), ('private', 'Xususiy'), ('foreign', 'Xorijiy filial'), ('joint', "Qo'shma")], default='state', max_length=20, verbose_name='Turi')),
                ('description', models.TextField(blank=True, verbose_name='Tavsif')),
                ('history', models.TextField(blank=True, verbose_name='Tarix')),
                ('logo', models.ImageField(blank=True, null=True, upload_to='universities/logos/', verbose_name='Logo')),
                ('cover_image', models.ImageField(blank=True, null=True, upload_to='universities/covers/', verbose_name='Muqova rasm')),
                ('website', models.URLField(blank=True, verbose_name='Veb sayt')),
                ('email', models.EmailField(blank=True, max_length=254, verbose_name='Email')),
                ('phone', models.CharField(blank=True, max_length=20, verbose_name='Telefon')),
                ('region', models.CharField(max_length=100, verbose_name='Viloyat')),
                ('city', models.CharField(max_length=100, verbose_name='Shahar')),
                ('address', models.TextField(blank=True, verbose_name='Manzil')),
                ('established_year', models.PositiveIntegerField(blank=True, null=True, verbose_name='Tashkil etilgan yil')),
                ('student_count', models.PositiveIntegerField(blank=True, null=True, verbose_name='Talabalar soni')),
                ('faculty_count', models.PositiveIntegerField(blank=True, null=True, verbose_name='Fakultetlar soni')),
                ('rating', models.FloatField(default=0.0, verbose_name='Reyting')),
                ('reviews_count', models.PositiveIntegerField(default=0, verbose_name='Sharhlar soni')),
                ('is_partner', models.BooleanField(default=False, verbose_name='Hamkor')),
                ('is_featured', models.BooleanField(default=False, verbose_name='Tavsiya etilgan')),
                ('is_active', models.BooleanField(default=True, verbose_name='Faol')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Universitet',
                'verbose_name_plural': 'Universitetlar',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Direction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('code', models.CharField(max_length=20, verbose_name='Kod')),
                ('name', models.CharField(max_length=300, verbose_name='Nomi')),
                ('slug', models.SlugField(verbose_name='Slug')),
                ('description', models.TextField(blank=True, verbose_name='Tavsif')),
                ('education_form', models.CharField(choices=[('full_time', 'Kunduzgi'), ('evening', 'Kechki'), ('distance', 'Sirtqi')], default='full_time', max_length=20, verbose_name="Ta'lim shakli")),
                ('education_type', models.CharField(choices=[('grant', 'Grant'), ('contract', 'Kontrakt'), ('both', 'Grant va Kontrakt')], default='both', max_length=20, verbose_name="Ta'lim turi")),
                ('duration_years', models.PositiveIntegerField(default=4, verbose_name='Davomiyligi (yil)')),
                ('grant_quota', models.PositiveIntegerField(default=0, verbose_name='Grant kvotasi')),
                ('contract_quota', models.PositiveIntegerField(default=0, verbose_name='Kontrakt kvotasi')),
                ('contract_price', models.DecimalField(decimal_places=2, default=0, max_digits=12, verbose_name='Kontrakt narxi')),
                ('is_active', models.BooleanField(default=True, verbose_name='Faol')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('required_subjects', models.ManyToManyField(related_name='required_for_directions', to='tests_app.subject', verbose_name='Majburiy fanlar')),
                ('faculty', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='directions', to='universities.faculty', verbose_name='Fakultet')),
                ('university', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='directions', to='universities.university', verbose_name='Universitet')),
            ],
            options={
                'verbose_name': "Yo'nalish",
                'verbose_name_plural': "Yo'nalishlar",
                'ordering': ['university', 'name'],
                'unique_together': {('university', 'code')},
            },
        ),
        migrations.CreateModel(
            name='AdmissionCalculation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('total_score', models.FloatField(verbose_name='Umumiy ball')),
                ('subject_scores', models.JSONField(default=dict, verbose_name='Fan ballari')),
                ('recommendations', models.JSONField(default=list, verbose_name='Tavsiyalar')),
                ('analysis', models.TextField(blank=True, verbose_name='AI tahlili')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='admission_calculations', to=settings.AUTH_USER_MODEL)),
                ('top_directions', models.ManyToManyField(blank=True, related_name='calculations', to='universities.direction')),
            ],
            options={
                'verbose_name': 'Qabul kalkulyatsiyasi',
                'verbose_name_plural': 'Qabul kalkulyatsiyalari',
                'ordering': ['-created_at'],
            },
        ),
        migrations.AddField(
            model_name='faculty',
            name='university',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='faculties', to='universities.university', verbose_name='Universitet'),
        ),
        migrations.CreateModel(
            name='PassingScore',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('year', models.PositiveIntegerField(verbose_name='Yil')),
                ('grant_score', models.FloatField(blank=True, null=True, verbose_name='Grant bali')),
                ('contract_score', models.FloatField(blank=True, null=True, verbose_name='Kontrakt bali')),
                ('total_applications', models.PositiveIntegerField(blank=True, null=True, verbose_name='Jami arizalar')),
                ('grant_accepted', models.PositiveIntegerField(blank=True, null=True, verbose_name='Grant qabul')),
                ('contract_accepted', models.PositiveIntegerField(blank=True, null=True, verbose_name='Kontrakt qabul')),
                ('competition_ratio', models.FloatField(blank=True, null=True, verbose_name='Tanlov nisbati')),
                ('direction', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='passing_scores', to='universities.direction', verbose_name="Yo'nalish")),
            ],
            options={
                'verbose_name': "O'tish bali",
                'verbose_name_plural': "O'tish ballari",
                'ordering': ['-year'],
                'unique_together': {('direction', 'year')},
            },
        ),
        migrations.AlterUniqueTogether(
            name='faculty',
            unique_together={('university', 'slug')},
        ),
        migrations.CreateModel(
            name='UniversityReview',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rating', models.PositiveIntegerField(validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(5)], verbose_name='Baho')),
                ('title', models.CharField(max_length=200, verbose_name='Sarlavha')),
                ('content', models.TextField(verbose_name='Sharh')),
                ('education_rating', models.PositiveIntegerField(default=3, verbose_name="Ta'lim sifati")),
                ('facility_rating', models.PositiveIntegerField(default=3, verbose_name='Jihozlanganlik')),
                ('staff_rating', models.PositiveIntegerField(default=3, verbose_name="O'qituvchilar")),
                ('is_approved', models.BooleanField(default=False, verbose_name='Tasdiqlangan')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('university', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reviews', to='universities.university', verbose_name='Universitet')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='university_reviews', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Sharh',
                'verbose_name_plural': 'Sharhlar',
                'ordering': ['-created_at'],
                'unique_together': {('university', 'user')},
            },
        ),
    ]
