# Generated by Django 5.2.10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('universities', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='university',
            name='short_name',
            field=models.CharField(blank=True, max_length=200, verbose_name='Qisqa nomi'),
        ),
    ]
