# Generated by Django 5.2.10 on 2026-01-19 05:11

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('tests_app', '0001_initial'),
        ('universities', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AIConversation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('conversation_type', models.CharField(choices=[('mentor', 'AI Mentor'), ('tutor', 'Mavzu tushuntirish'), ('advisor', 'Universitet maslahati'), ('analyzer', 'Test tahlili')], default='mentor', max_length=20, verbose_name='Suhbat turi')),
                ('title', models.CharField(blank=True, max_length=200, verbose_name='Sarlavha')),
                ('message_count', models.PositiveIntegerField(default=0, verbose_name='Xabarlar soni')),
                ('is_active', models.BooleanField(default=True, verbose_name='Faol')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('subject', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='ai_conversations', to='tests_app.subject')),
                ('test_attempt', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='ai_conversations', to='tests_app.testattempt')),
                ('topic', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='ai_conversations', to='tests_app.topic')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ai_conversations', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'AI Suhbat',
                'verbose_name_plural': 'AI Suhbatlar',
                'ordering': ['-updated_at'],
            },
        ),
        migrations.CreateModel(
            name='AIMessage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('role', models.CharField(choices=[('user', 'Foydalanuvchi'), ('assistant', 'AI'), ('system', 'Tizim')], max_length=20, verbose_name='Rol')),
                ('content', models.TextField(verbose_name='Matn')),
                ('model_used', models.CharField(blank=True, max_length=50, verbose_name='Ishlatilgan model')),
                ('tokens_used', models.PositiveIntegerField(default=0, verbose_name='Tokenlar')),
                ('is_helpful', models.BooleanField(blank=True, null=True, verbose_name='Foydali')),
                ('feedback', models.TextField(blank=True, verbose_name='Fikr-mulohaza')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('conversation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='messages', to='ai_core.aiconversation')),
            ],
            options={
                'verbose_name': 'AI Xabar',
                'verbose_name_plural': 'AI Xabarlar',
                'ordering': ['created_at'],
            },
        ),
        migrations.CreateModel(
            name='AIRecommendation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('recommendation_type', models.CharField(choices=[('study', "O'qish tavsiyasi"), ('topic', 'Mavzu tavsiyasi'), ('university', 'Universitet tavsiyasi'), ('strategy', 'Strategiya'), ('motivation', 'Motivatsiya')], max_length=20, verbose_name='Turi')),
                ('priority', models.CharField(choices=[('low', 'Past'), ('medium', "O'rta"), ('high', 'Yuqori'), ('critical', 'Muhim')], default='medium', max_length=20, verbose_name='Muhimlik')),
                ('title', models.CharField(max_length=200, verbose_name='Sarlavha')),
                ('content', models.TextField(verbose_name='Mazmun')),
                ('action_url', models.CharField(blank=True, max_length=500, verbose_name='Havola')),
                ('action_text', models.CharField(blank=True, max_length=100, verbose_name='Tugma matni')),
                ('is_read', models.BooleanField(default=False, verbose_name="O'qilgan")),
                ('is_dismissed', models.BooleanField(default=False, verbose_name='Yopilgan')),
                ('is_completed', models.BooleanField(default=False, verbose_name='Bajarilgan')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('expires_at', models.DateTimeField(blank=True, null=True, verbose_name='Amal qilish muddati')),
                ('subject', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='tests_app.subject')),
                ('topic', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='tests_app.topic')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ai_recommendations', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'AI Tavsiya',
                'verbose_name_plural': 'AI Tavsiyalar',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='StudyPlan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('title', models.CharField(max_length=200, verbose_name='Sarlavha')),
                ('description', models.TextField(blank=True, verbose_name='Tavsif')),
                ('target_exam_date', models.DateField(blank=True, null=True, verbose_name='Imtihon sanasi')),
                ('target_score', models.PositiveIntegerField(blank=True, null=True, verbose_name='Maqsadli ball')),
                ('daily_hours', models.FloatField(default=2.0, verbose_name='Kunlik soatlar')),
                ('weekly_days', models.PositiveIntegerField(default=6, verbose_name='Haftalik kunlar')),
                ('status', models.CharField(choices=[('active', 'Faol'), ('paused', "To'xtatilgan"), ('completed', 'Yakunlangan'), ('abandoned', 'Tashlab ketilgan')], default='active', max_length=20, verbose_name='Holat')),
                ('total_tasks', models.PositiveIntegerField(default=0, verbose_name='Jami vazifalar')),
                ('completed_tasks', models.PositiveIntegerField(default=0, verbose_name='Bajarilgan vazifalar')),
                ('progress_percentage', models.FloatField(default=0.0, verbose_name='Progress (%)')),
                ('ai_analysis', models.TextField(blank=True, verbose_name='AI tahlili')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('subjects', models.ManyToManyField(related_name='study_plans', to='tests_app.subject')),
                ('target_direction', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='universities.direction')),
                ('target_university', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='universities.university')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='study_plans', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': "O'quv reja",
                'verbose_name_plural': "O'quv rejalar",
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='StudyPlanTask',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='Sarlavha')),
                ('description', models.TextField(blank=True, verbose_name='Tavsif')),
                ('task_type', models.CharField(choices=[('study', "O'qish"), ('test', 'Test yechish'), ('review', 'Takrorlash'), ('practice', 'Mashq')], default='study', max_length=20, verbose_name='Turi')),
                ('scheduled_date', models.DateField(verbose_name='Rejalashtirilgan sana')),
                ('estimated_minutes', models.PositiveIntegerField(default=30, verbose_name='Taxminiy vaqt (daqiqa)')),
                ('is_completed', models.BooleanField(default=False, verbose_name='Bajarilgan')),
                ('completed_at', models.DateTimeField(blank=True, null=True, verbose_name='Bajarilgan vaqt')),
                ('actual_minutes', models.PositiveIntegerField(blank=True, null=True, verbose_name='Sarflangan vaqt')),
                ('order', models.PositiveIntegerField(default=0, verbose_name='Tartib')),
                ('study_plan', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tasks', to='ai_core.studyplan')),
                ('subject', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='tests_app.subject')),
                ('test', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='tests_app.test')),
                ('topic', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='tests_app.topic')),
            ],
            options={
                'verbose_name': 'Reja vazifasi',
                'verbose_name_plural': 'Reja vazifalari',
                'ordering': ['scheduled_date', 'order'],
            },
        ),
        migrations.CreateModel(
            name='WeakTopicAnalysis',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('total_questions', models.PositiveIntegerField(default=0, verbose_name='Jami savollar')),
                ('correct_answers', models.PositiveIntegerField(default=0, verbose_name="To'g'ri javoblar")),
                ('accuracy_rate', models.FloatField(default=0.0, verbose_name="To'g'rilik (%)")),
                ('recommendation', models.TextField(blank=True, verbose_name='AI tavsiyasi')),
                ('priority_score', models.FloatField(default=0.0, verbose_name='Muhimlik bali')),
                ('last_updated', models.DateTimeField(auto_now=True)),
                ('subject', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tests_app.subject')),
                ('topic', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tests_app.topic')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='weak_topics', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Sust mavzu',
                'verbose_name_plural': 'Sust mavzular',
                'ordering': ['accuracy_rate'],
                'unique_together': {('user', 'topic')},
            },
        ),
    ]
