# Generated by Django 5.2.1 on 2026-02-22 11:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ai_core', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='studyplantask',
            name='questions_count',
            field=models.PositiveIntegerField(blank=True, null=True, verbose_name='Savollar soni'),
        ),
    ]
